# Generated by Django 2.2.20 on 2021-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpBitCandleMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=30, verbose_name='마켓명')),
                ('candle_date_time_utc', models.DateTimeField(blank=True, null=True, verbose_name='캔들 기준 시각(UTC 기준)')),
                ('candle_date_time_kst', models.DateTimeField(unique=True, verbose_name='캔들 기준 시각(KST 기준)')),
                ('opening_price', models.FloatField(verbose_name='시가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('trade_price', models.FloatField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
                ('timestamp', models.CharField(blank=True, max_length=130, null=True, verbose_name='해당 캔들에서 마지막 틱이 저장된 시각')),
                ('candle_acc_trade_price', models.FloatField(blank=True, null=True, verbose_name='누적 거래 금액')),
                ('candle_acc_trade_volume', models.FloatField(blank=True, null=True, verbose_name='누적 거래량')),
                ('unit', models.IntegerField(blank=True, null=True, verbose_name='분 단위(유닌)')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '업비트 현제 시세 분봉',
                'verbose_name_plural': '업비트 현제 시세 분봉 목록',
                'ordering': ['-pk'],
            },
        ),
    ]
