bits_name_list = [
    {'market': 'KRW-BTC', 'korean_name': '비트코인', 'english_name': 'Bitcoin'},
    {'market': 'BTC-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum'},
    {'market': 'BTC-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin'},
    {'market': 'BTC-XRP', 'korean_name': '리플', 'english_name': 'Ripple'},
    {'market': 'BTC-ETC',
     'korean_name': '이더리움클래식',
     'english_name': 'Ethereum Classic'},
    {'market': 'BTC-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo'},
    {'market': 'BTC-CVC', 'korean_name': '시빅', 'english_name': 'Civic'},
    {'market': 'BTC-DGB', 'korean_name': '디지바이트', 'english_name': 'DigiByte'},
    {'market': 'BTC-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin'},
    {'market': 'BTC-SNT',
     'korean_name': '스테이터스네트워크토큰',
     'english_name': 'Status Network Token'},
    {'market': 'BTC-WAVES', 'korean_name': '웨이브', 'english_name': 'Waves'},
    {'market': 'BTC-NMR', 'korean_name': '뉴메레르', 'english_name': 'Numeraire'},
    {'market': 'BTC-XEM', 'korean_name': '넴', 'english_name': 'NEM'},
    {'market': 'BTC-LBC',
     'korean_name': '엘비알와이크레딧',
     'english_name': 'LBRY Credits'},
    {'market': 'BTC-QTUM', 'korean_name': '퀀텀', 'english_name': 'Qtum'},
    {'market': 'BTC-NXT', 'korean_name': '엔엑스티', 'english_name': 'Nxt'},
    {'market': 'BTC-BAT',
     'korean_name': '베이직어텐션토큰',
     'english_name': 'Basic Attention Token'},
    {'market': 'BTC-LSK', 'korean_name': '리스크', 'english_name': 'Lisk'},
    {'market': 'BTC-RDD', 'korean_name': '레드코인', 'english_name': 'ReddCoin'},
    {'market': 'BTC-STEEM', 'korean_name': '스팀', 'english_name': 'Steem'},
    {'market': 'BTC-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin'},
    {'market': 'BTC-BNT', 'korean_name': '뱅코르', 'english_name': 'Bancor'},
    {'market': 'BTC-XLM', 'korean_name': '스텔라루멘', 'english_name': 'Lumen'},
    {'market': 'BTC-ARDR', 'korean_name': '아더', 'english_name': 'Ardor'},
    {'market': 'BTC-KMD', 'korean_name': '코모도', 'english_name': 'Komodo'},
    {'market': 'BTC-ARK', 'korean_name': '아크', 'english_name': 'Ark'},
    {'market': 'BTC-ADX', 'korean_name': '애드엑스', 'english_name': 'AdEx'},
    {'market': 'BTC-SYS', 'korean_name': '시스코인', 'english_name': 'SysCoin'},
    {'market': 'BTC-ANT', 'korean_name': '아라곤', 'english_name': 'Aragon'},
    {'market': 'BTC-STORJ', 'korean_name': '스토리지', 'english_name': 'Storj'},
    {'market': 'BTC-GRS', 'korean_name': '그로스톨코인', 'english_name': 'Groestlcoin'},
    {'market': 'BTC-REP', 'korean_name': '어거', 'english_name': 'Augur'},
    {'market': 'BTC-RLC', 'korean_name': '아이젝', 'english_name': 'iEx.ec'},
    {'market': 'BTC-EMC2',
     'korean_name': '아인스타이늄',
     'english_name': 'Einsteinium'},
    {'market': 'BTC-ADA', 'korean_name': '에이다', 'english_name': 'Ada'},
    {'market': 'BTC-MANA',
     'korean_name': '디센트럴랜드',
     'english_name': 'Decentraland'},
    {'market': 'BTC-SBD', 'korean_name': '스팀달러', 'english_name': 'SteemDollars'},
    {'market': 'BTC-RCN',
     'korean_name': '리피오크레딧네트워크',
     'english_name': 'Ripio Credit Network'},
    {'market': 'BTC-POWR', 'korean_name': '파워렛저', 'english_name': 'Power ledger'},
    {'market': 'BTC-DNT', 'korean_name': '디스트릭트0x', 'english_name': 'district0x'},
    {'market': 'BTC-IGNIS', 'korean_name': '이그니스', 'english_name': 'Ignis'},
    {'market': 'BTC-ZRX', 'korean_name': '제로엑스', 'english_name': '0x Protocol'},
    {'market': 'BTC-TRX', 'korean_name': '트론', 'english_name': 'TRON'},
    {'market': 'BTC-TUSD', 'korean_name': '트루USD', 'english_name': 'TrueUSD'},
    {'market': 'BTC-LRC', 'korean_name': '루프링', 'english_name': 'Loopring'},
    {'market': 'BTC-DMT', 'korean_name': '디마켓', 'english_name': 'DMarket'},
    {'market': 'BTC-POLY', 'korean_name': '폴리매쓰', 'english_name': 'Polymath'},
    {'market': 'BTC-PRO', 'korean_name': '프로피', 'english_name': 'Propy'},
    {'market': 'BTC-BCH',
     'korean_name': '비트코인캐시',
     'english_name': 'Bitcoin Cash'},
    {'market': 'BTC-MFT', 'korean_name': '메인프레임', 'english_name': 'Mainframe'},
    {'market': 'BTC-LOOM',
     'korean_name': '룸네트워크',
     'english_name': 'Loom Network'},
    {'market': 'BTC-RFR', 'korean_name': '리퍼리움', 'english_name': 'Refereum'},
    {'market': 'BTC-RVN', 'korean_name': '레이븐코인', 'english_name': 'Ravencoin'},
    {'market': 'BTC-BFT',
     'korean_name': '비에프토큰',
     'english_name': 'BnkToTheFuture'},
    {'market': 'BTC-GO', 'korean_name': '고체인', 'english_name': 'GoChain'},
    {'market': 'BTC-UPP',
     'korean_name': '센티넬프로토콜',
     'english_name': 'Sentinel Protocol'},
    {'market': 'BTC-ENJ', 'korean_name': '엔진코인', 'english_name': 'Enjin'},
    {'market': 'BTC-EDR', 'korean_name': '엔도르', 'english_name': 'Endor'},
    {'market': 'BTC-MTL', 'korean_name': '메탈', 'english_name': 'Metal'},
    {'market': 'BTC-PAX',
     'korean_name': '팩소스스탠다드',
     'english_name': 'Paxos Standard'},
    {'market': 'BTC-MOC', 'korean_name': '모스코인', 'english_name': 'Moss Coin'},
    {'market': 'BTC-ZIL', 'korean_name': '질리카', 'english_name': 'Zilliqa'},
    {'market': 'BTC-BSV',
     'korean_name': '비트코인에스브이',
     'english_name': 'Bitcoin SV'},
    {'market': 'BTC-IOST', 'korean_name': '아이오에스티', 'english_name': 'IOST'},
    {'market': 'BTC-NCASH',
     'korean_name': '뉴클리어스비전',
     'english_name': 'Nucleus Vision'},
    {'market': 'BTC-DENT', 'korean_name': '덴트', 'english_name': 'Dent'},
    {'market': 'BTC-ELF', 'korean_name': '엘프', 'english_name': 'aelf'},
    {'market': 'BTC-BTT', 'korean_name': '비트토렌트', 'english_name': 'BitTorrent'},
    {'market': 'BTC-VITE', 'korean_name': '비트토큰', 'english_name': 'Vite'},
    {'market': 'BTC-IOTX', 'korean_name': '아이오텍스', 'english_name': 'IoTeX'},
    {'market': 'BTC-SOLVE', 'korean_name': '솔브케어', 'english_name': 'Solve.Care'},
    {'market': 'BTC-NKN', 'korean_name': '엔케이엔', 'english_name': 'NKN'},
    {'market': 'BTC-META', 'korean_name': '메타디움', 'english_name': 'Metadium'},
    {'market': 'BTC-ANKR', 'korean_name': '앵커', 'english_name': 'Ankr'},
    {'market': 'BTC-CRO',
     'korean_name': '크립토닷컴체인',
     'english_name': 'Crypto.com Chain'},
    {'market': 'BTC-FSN', 'korean_name': '퓨전', 'english_name': 'Fusion'},
    {'market': 'BTC-ORBS', 'korean_name': '오브스', 'english_name': 'Orbs'},
    {'market': 'BTC-AERGO', 'korean_name': '아르고', 'english_name': 'Aergo'},
    {'market': 'BTC-PI', 'korean_name': '플리안', 'english_name': 'Plian'},
    {'market': 'BTC-ATOM', 'korean_name': '코스모스', 'english_name': 'Cosmos'},
    {'market': 'BTC-STPT',
     'korean_name': '에스티피',
     'english_name': 'Standard Tokenization Protocol'},
    {'market': 'BTC-LAMB', 'korean_name': '람다', 'english_name': 'Lambda'},
    {'market': 'BTC-EOS', 'korean_name': '이오스', 'english_name': 'EOS'},
    {'market': 'BTC-LUNA', 'korean_name': '루나', 'english_name': 'Luna'},
    {'market': 'BTC-DAI', 'korean_name': '다이', 'english_name': 'Dai'},
    {'market': 'BTC-MKR', 'korean_name': '메이커', 'english_name': 'Maker'},
    {'market': 'BTC-BORA', 'korean_name': '보라', 'english_name': 'BORA'},
    {'market': 'BTC-TSHP', 'korean_name': '트웰브쉽스', 'english_name': '12SHIPS'},
    {'market': 'BTC-WAXP', 'korean_name': '왁스', 'english_name': 'WAX'},
    {'market': 'BTC-MED', 'korean_name': '메디블록', 'english_name': 'MediBloc'},
    {'market': 'BTC-MLK', 'korean_name': '밀크', 'english_name': 'MiL.k'},
    {'market': 'BTC-PXL', 'korean_name': '픽셀', 'english_name': 'PIXEL'},
    {'market': 'BTC-VET', 'korean_name': '비체인', 'english_name': 'VeChain'},
    {'market': 'BTC-CHZ', 'korean_name': '칠리즈', 'english_name': 'Chiliz'},
    {'market': 'BTC-FX', 'korean_name': '펑션엑스', 'english_name': 'Function X'},
    {'market': 'BTC-OGN',
     'korean_name': '오리진프로토콜',
     'english_name': 'Origin Protocol'},
    {'market': 'BTC-ITAM', 'korean_name': '아이텀', 'english_name': 'ITAM'},
    {'market': 'BTC-XTZ', 'korean_name': '테조스', 'english_name': 'Tezos'},
    {'market': 'BTC-HIVE', 'korean_name': '하이브', 'english_name': 'Hive'},
    {'market': 'BTC-HBD', 'korean_name': '하이브달러', 'english_name': 'Hive Dollar'},
    {'market': 'BTC-OBSR', 'korean_name': '옵저버', 'english_name': 'Observer'},
    {'market': 'BTC-DKA', 'korean_name': '디카르고', 'english_name': 'dKargo'},
    {'market': 'BTC-STMX', 'korean_name': '스톰엑스', 'english_name': 'StormX'},
    {'market': 'BTC-AHT', 'korean_name': '아하토큰', 'english_name': 'AhaToken'},
    {'market': 'BTC-PCI', 'korean_name': '페이코인', 'english_name': 'PayCoin'},
    {'market': 'BTC-RINGX', 'korean_name': '링엑스', 'english_name': 'RINGX'},
    {'market': 'BTC-LINK', 'korean_name': '체인링크', 'english_name': 'Chainlink'},
    {'market': 'BTC-KAVA', 'korean_name': '카바', 'english_name': 'Kava'},
    {'market': 'BTC-JST', 'korean_name': '저스트', 'english_name': 'JUST'},
    {'market': 'BTC-CHR', 'korean_name': '크로미아', 'english_name': 'Chromia'},
    {'market': 'BTC-DAD', 'korean_name': '다드', 'english_name': 'DAD'},
    {'market': 'BTC-TON', 'korean_name': '톤', 'english_name': 'TON'},
    {'market': 'BTC-CTSI', 'korean_name': '카르테시', 'english_name': 'Cartesi'},
    {'market': 'BTC-DOT', 'korean_name': '폴카닷', 'english_name': 'Polkadot'},
    {'market': 'BTC-COMP', 'korean_name': '컴파운드', 'english_name': 'Compound'},
    {'market': 'BTC-SXP', 'korean_name': '스와이프', 'english_name': 'Swipe'},
    {'market': 'BTC-HUNT', 'korean_name': '헌트', 'english_name': 'HUNT'},
    {'market': 'BTC-ONIT', 'korean_name': '온버프', 'english_name': 'ONBUFF'},
    {'market': 'BTC-CRV', 'korean_name': '커브', 'english_name': 'Curve'},
    {'market': 'BTC-ALGO', 'korean_name': '알고랜드', 'english_name': 'Algorand'},
    {'market': 'BTC-RSR',
     'korean_name': '리저브라이트',
     'english_name': 'Reserve Rights'},
    {'market': 'BTC-OXT', 'korean_name': '오키드', 'english_name': 'Orchid'},
    {'market': 'BTC-PLA', 'korean_name': '플레이댑', 'english_name': 'PlayDapp'},
    {'market': 'BTC-MARO', 'korean_name': '마로', 'english_name': 'Maro'},
    {'market': 'BTC-SAND', 'korean_name': '샌드박스', 'english_name': 'The Sandbox'},
    {'market': 'BTC-SUN', 'korean_name': '썬', 'english_name': 'SUN'},
    {'market': 'BTC-SRM', 'korean_name': '세럼', 'english_name': 'Serum'},
    {'market': 'BTC-QTCON', 'korean_name': '퀴즈톡', 'english_name': 'Quiztok'},
    {'market': 'BTC-MVL', 'korean_name': '엠블', 'english_name': 'MVL'},
    {'market': 'BTC-GXC', 'korean_name': '지엑스체인', 'english_name': 'GXChain'},
    {'market': 'BTC-AQT',
     'korean_name': '알파쿼크',
     'english_name': 'Alpha Quark Token'},
    {'market': 'BTC-AXS',
     'korean_name': '엑시인피니티',
     'english_name': 'Axie Infinity'},
    {'market': 'BTC-STRAX', 'korean_name': '스트라티스', 'english_name': 'Stratis'},
    {'market': 'BTC-BCHA',
     'korean_name': '비트코인캐시에이비씨',
     'english_name': 'Bitcoin Cash ABC'},
    {'market': 'BTC-GLM', 'korean_name': '골렘', 'english_name': 'Golem'},
    {'market': 'BTC-FCT2', 'korean_name': '피르마체인', 'english_name': 'FirmaChain'},
    {'market': 'BTC-SSX', 'korean_name': '썸씽', 'english_name': 'SOMESING'},
    {'market': 'BTC-FIL', 'korean_name': '파일코인', 'english_name': 'Filecoin'},
    {'market': 'BTC-UNI', 'korean_name': '유니스왑', 'english_name': 'Uniswap'},
    {'market': 'BTC-BASIC', 'korean_name': '베이직', 'english_name': 'Basic'},
    {'market': 'BTC-INJ',
     'korean_name': '인젝티브프로토콜',
     'english_name': 'Injective Protocol'},
    {'market': 'BTC-PROM', 'korean_name': '프로메테우스', 'english_name': 'Prometeus'},
    {'market': 'BTC-VAL', 'korean_name': '밸리디티', 'english_name': 'Validity'},
    {'market': 'BTC-PSG',
     'korean_name': '파리생제르맹',
     'english_name': 'Paris Saint-Germain Fan Token'},
    {'market': 'BTC-JUV',
     'korean_name': '유벤투스',
     'english_name': 'Juventus Fan Token'},
    {'market': 'BTC-CBK', 'korean_name': '코박토큰', 'english_name': 'Cobak Token'},
    {'market': 'BTC-FOR', 'korean_name': '포튜브', 'english_name': 'ForTube'},
    {'market': 'BTC-BFC', 'korean_name': '바이프로스트', 'english_name': 'Bifrost'},
    {'market': 'BTC-LINA', 'korean_name': '리니어파이낸스', 'english_name': 'Linear'},
    {'market': 'BTC-HUM', 'korean_name': '휴먼스케이프', 'english_name': 'Humanscape'},
    {'market': 'BTC-PICA', 'korean_name': '피카', 'english_name': 'Pica'},
    {'market': 'BTC-CELO', 'korean_name': '셀로', 'english_name': 'Celo'},
    {'market': 'BTC-IQ', 'korean_name': '에브리피디아', 'english_name': 'Everipedia'},
    {'market': 'BTC-STX', 'korean_name': '스택스', 'english_name': 'Stacks'},
    {'market': 'BTC-NEAR',
     'korean_name': '니어프로토콜',
     'english_name': 'NEAR Protocol'},
    {'market': 'BTC-AUCTION', 'korean_name': '바운스토큰', 'english_name': 'Bounce'},
    {'market': 'BTC-DAWN',
     'korean_name': '던프로토콜',
     'english_name': 'Dawn Protocol'},
    {'market': 'BTC-FLOW', 'korean_name': '플로우', 'english_name': 'Flow'},
    {'market': 'BTC-STRK', 'korean_name': '스트라이크', 'english_name': 'Strike'},
    {'market': 'BTC-PUNDIX', 'korean_name': '펀디엑스', 'english_name': 'Pundi X'}
]

market_withdraw_fee_info = [
    {'coin': 'ADA',
     'withdraw_fee': '0.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ADX',
     'withdraw_fee': '14',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'AERGO',
     'withdraw_fee': '50',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ALGO',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ANKR',
     'withdraw_fee': '150',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ANT',
     'withdraw_fee': '1.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ARDR',
     'withdraw_fee': '2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ARK',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ATOM',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'AUCTION',
     'withdraw_fee': '0.4',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'AXS',
     'withdraw_fee': '3',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BAT',
     'withdraw_fee': '20',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BCH',
     'withdraw_fee': '0.001',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BCHA',
     'withdraw_fee': '0.001',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BNT',
     'withdraw_fee': '3',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BTC',
     'withdraw_fee': '0.0009',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BTG',
     'withdraw_fee': '0.001',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BTM',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BTS',
     'withdraw_fee': '5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'BTT',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CBK',
     'withdraw_fee': '1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CELO',
     'withdraw_fee': '2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CHZ',
     'withdraw_fee': '50',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CLOAK',
     'withdraw_fee': '0.02',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'COMP',
     'withdraw_fee': '0.04',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CRV',
     'withdraw_fee': '5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CTSI',
     'withdraw_fee': '45',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'CVC',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DAI',
     'withdraw_fee': '15',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DASH',
     'withdraw_fee': '0.002',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DCR',
     'withdraw_fee': '0.05',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DENT',
     'withdraw_fee': '1500.00',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DGB',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DNT',
     'withdraw_fee': '60',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DOGE',
     'withdraw_fee': '2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DON',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'DOT',
     'withdraw_fee': '1.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ELF',
     'withdraw_fee': '40',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ENG',
     'withdraw_fee': '1.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ENJ',
     'withdraw_fee': '13',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'EOS',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ETC',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ETH',
     'withdraw_fee': '0.018',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'FIL',
     'withdraw_fee': '0.15',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'FOR',
     'withdraw_fee': '200',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'FUN',
     'withdraw_fee': '60',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'GAS',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'GLM',
     'withdraw_fee': '25',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'GO',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'GRS',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'HBAR',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ICX',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'INJ',
     'withdraw_fee': '1.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'IOST',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'IOTA',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'IOTX',
     'withdraw_fee': '110',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'IQ',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'JST',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'KAVA',
     'withdraw_fee': '1.7',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'KMD',
     'withdraw_fee': '0.002',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'KNC',
     'withdraw_fee': '7',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LINA',
     'withdraw_fee': '200',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LINK',
     'withdraw_fee': '0.6',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LOOM',
     'withdraw_fee': '90',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LRC',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LSK',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LTC',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LUN',
     'withdraw_fee': '0.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'LUNA',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MANA',
     'withdraw_fee': '35',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MBL',
     'withdraw_fee': '600',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MCO',
     'withdraw_fee': '0.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MFT',
     'withdraw_fee': '600',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MKR',
     'withdraw_fee': '0.005',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'MTL',
     'withdraw_fee': '3',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NAV',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NCASH',
     'withdraw_fee': '2200.00',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NEAR',
     'withdraw_fee': '2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NEO',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NKN',
     'withdraw_fee': '50',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NMR',
     'withdraw_fee': '0.4',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'NXS',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'OGN',
     'withdraw_fee': '10',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'OMG',
     'withdraw_fee': '2.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ONG',
     'withdraw_fee': '1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ONT',
     'withdraw_fee': '0.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ONX',
     'withdraw_fee': '2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'OST',
     'withdraw_fee': '60',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'OXT',
     'withdraw_fee': '25',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'PIVX',
     'withdraw_fee': '0.03',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'POLY',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'POWR',
     'withdraw_fee': '28',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'PROM',
     'withdraw_fee': '1.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'QKC',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'QTUM',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'RCN',
     'withdraw_fee': '110',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'REP',
     'withdraw_fee': '0.45',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'RLC',
     'withdraw_fee': '6.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'RSR',
     'withdraw_fee': '214',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'RVN',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SALT',
     'withdraw_fee': '1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SAND',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SC',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SNGLS',
     'withdraw_fee': '3.5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SNT',
     'withdraw_fee': '130',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SRM',
     'withdraw_fee': '3',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STEEM',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STMX',
     'withdraw_fee': '310',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STORJ',
     'withdraw_fee': '5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STPT',
     'withdraw_fee': '250',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STRAX',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'STX',
     'withdraw_fee': '10',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SUN',
     'withdraw_fee': '0.0018',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SXP',
     'withdraw_fee': '5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'SYS',
     'withdraw_fee': '0.0002',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'TFUEL',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'THETA',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'TRX',
     'withdraw_fee': '0',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'UNI',
     'withdraw_fee': '0.6',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'VET',
     'withdraw_fee': '100',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'VIA',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'VIB',
     'withdraw_fee': '17',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'VITE',
     'withdraw_fee': '30',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'VTHO',
     'withdraw_fee': '100',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'WAVES',
     'withdraw_fee': '0.001',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'WINGS',
     'withdraw_fee': '6',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XEM',
     'withdraw_fee': '4',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XLM',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XMR',
     'withdraw_fee': '0.04',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XPR',
     'withdraw_fee': '5',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XRP',
     'withdraw_fee': '1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XTZ',
     'withdraw_fee': '0.1',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'XVG',
     'withdraw_fee': '0.2',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ZEN',
     'withdraw_fee': '0.002',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ZIL',
     'withdraw_fee': '0.01',
     'deposit': '0',
     'minimum_with_draw_amount': None},
    {'coin': 'ZRX',
     'withdraw_fee': '10',
     'deposit': '0',
     'minimum_with_draw_amount': None}
]
status_withdraw = [
    {'currency': 'BTC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 680893,
     'block_updated_at': '2021-04-28T01:04:44.708+00:00', 'block_elapsed_minutes': 6},
    {'currency': 'POWR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'OMG', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ETH', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:02.446+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ETC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12634559,
     'block_updated_at': '2021-04-28T01:06:36.697+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'SNT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'REP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STORJ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LTC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 2042479,
     'block_updated_at': '2021-04-28T01:06:42.057+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'MTL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'QTUM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 843514,
     'block_updated_at': '2021-04-28T01:06:55.750+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XRP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 63193736,
     'block_updated_at': '2021-04-28T01:07:23.579+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BTG', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 683650,
     'block_updated_at': '2021-04-28T00:29:40.197+00:00', 'block_elapsed_minutes': 41},
    {'currency': 'WAVES', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 2566264,
     'block_updated_at': '2021-04-28T01:06:01.685+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'ANT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MANA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'WAXP', 'wallet_state': 'paused', 'block_state': 'inactive', 'block_height': 116098972,
     'block_updated_at': '2021-04-27T06:20:07.601+00:00', 'block_elapsed_minutes': 1130},
    {'currency': 'ZRX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STEEM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 53265242,
     'block_updated_at': '2021-04-28T01:07:24.343+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SBD', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 53265242,
     'block_updated_at': '2021-04-28T01:07:24.343+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'EOS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BAT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BNT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RCN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'NMR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DNT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'USDT', 'wallet_state': 'unsupported', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CVC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RLC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ADX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ADA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 5646968,
     'block_updated_at': '2021-04-28T01:06:36.424+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'TRX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 29709510,
     'block_updated_at': '2021-04-28T01:07:16.576+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'NEO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 7269491,
     'block_updated_at': '2021-04-28T01:07:21.843+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'TUSD', 'wallet_state': 'unsupported', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LRC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ARK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 16029678,
     'block_updated_at': '2021-04-28T01:07:07.127+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ARDR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1769085,
     'block_updated_at': '2021-04-28T01:07:08.937+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'IGNIS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1769085,
     'block_updated_at': '2021-04-28T01:07:08.937+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'KMD', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 2368779,
     'block_updated_at': '2021-04-28T01:06:53.912+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LSK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 15281046,
     'block_updated_at': '2021-04-28T01:07:21.182+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'EMC2', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3821069,
     'block_updated_at': '2021-04-28T01:07:14.396+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XEM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3172441,
     'block_updated_at': '2021-04-28T01:05:58.190+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'GRS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3564860,
     'block_updated_at': '2021-04-28T01:05:33.648+00:00', 'block_elapsed_minutes': 5},
    {'currency': 'ICX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 33668331,
     'block_updated_at': '2021-04-28T01:07:24.124+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DMT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XLM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 35139395,
     'block_updated_at': '2021-04-28T01:07:18.866+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RDD', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3785385,
     'block_updated_at': '2021-04-28T01:06:51.589+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'SC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 309939,
     'block_updated_at': '2021-04-28T00:20:54.698+00:00', 'block_elapsed_minutes': 49},
    {'currency': 'ONT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12015372,
     'block_updated_at': '2021-04-28T01:07:23.440+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'POLY', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ELF', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PRO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'EOSDAC', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DOGE', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3706326,
     'block_updated_at': '2021-04-28T01:07:03.149+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SYS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1000372,
     'block_updated_at': '2021-04-28T01:07:24.626+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'GAS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 7269491,
     'block_updated_at': '2021-04-28T01:07:21.843+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ZIL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1132354,
     'block_updated_at': '2021-04-28T01:06:53.341+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'IOTA', 'wallet_state': 'paused', 'block_state': 'inactive', 'block_height': None,
     'block_updated_at': '2021-02-10T17:48:32.760+00:00', 'block_elapsed_minutes': 109882},
    {'currency': 'LOOM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BCH', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 685321,
     'block_updated_at': '2021-04-28T01:00:58.908+00:00', 'block_elapsed_minutes': 9},
    {'currency': 'NXT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3427728,
     'block_updated_at': '2021-04-28T01:07:12.828+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ADD', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MFT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'IOST', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 134471950,
     'block_updated_at': '2021-04-28T01:07:21.034+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RFR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'IQ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ONG', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12015372,
     'block_updated_at': '2021-04-28T01:07:23.440+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RVN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1730079,
     'block_updated_at': '2021-04-28T01:07:19.636+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LBC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 952643,
     'block_updated_at': '2021-04-28T01:04:50.920+00:00', 'block_elapsed_minutes': 6},
    {'currency': 'DGB', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12845340,
     'block_updated_at': '2021-04-28T01:07:19.505+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BFT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'UPP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ENJ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'EDR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HORUS', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MEETONE', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'GO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 18616570,
     'block_updated_at': '2021-04-28T01:07:20.321+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CHL', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BLACK', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 180831300,
     'block_updated_at': '2021-04-28T01:07:22.242+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'KNC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'VET', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 8906262,
     'block_updated_at': '2021-04-28T01:07:16.670+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'VTHO', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 8906262,
     'block_updated_at': '2021-04-28T01:07:16.670+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MOC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 58939833,
     'block_updated_at': '2021-04-28T01:07:24.316+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PAX', 'wallet_state': 'unsupported', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BSV', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 684802,
     'block_updated_at': '2021-04-28T00:59:35.179+00:00', 'block_elapsed_minutes': 11},
    {'currency': 'NCASH', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SOLVE', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'THETA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 10131371,
     'block_updated_at': '2021-04-28T01:07:24.264+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XTZ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1447810,
     'block_updated_at': '2021-04-28T01:07:09.695+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DENT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'QKC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1096387,
     'block_updated_at': '2021-04-28T01:07:03.562+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'VITE', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 59759064,
     'block_updated_at': '2021-04-28T01:07:25.223+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'IOTX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 10813231,
     'block_updated_at': '2021-04-28T01:07:20.552+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BTT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 29709510,
     'block_updated_at': '2021-04-28T01:07:16.576+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'NKN', 'wallet_state': 'paused', 'block_state': 'inactive', 'block_height': 2575437,
     'block_updated_at': '2021-04-28T01:07:03.890+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'META', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 18123182,
     'block_updated_at': '2021-04-28T01:07:24.039+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'FSN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 4408297,
     'block_updated_at': '2021-04-28T01:07:11.660+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ANKR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CRO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'AERGO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PI', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 23672262,
     'block_updated_at': '2021-04-28T01:07:24.699+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'TFUEL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 10131371,
     'block_updated_at': '2021-04-28T01:07:24.264+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PLA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ORBS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BORA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ACN', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 21172287,
     'block_updated_at': '2021-04-28T01:07:22.373+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ATOM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 6019494,
     'block_updated_at': '2021-04-28T01:07:17.834+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'TT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 67899683,
     'block_updated_at': '2021-04-28T01:07:24.554+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CRE', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LUNA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 2751099,
     'block_updated_at': '2021-04-28T01:07:19.830+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LAMB', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STPT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MKR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DAI', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MBL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12015372,
     'block_updated_at': '2021-04-28T01:07:23.440+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'FX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PROM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CHR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PXL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 57868828,
     'block_updated_at': '2021-04-28T01:07:24.910+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'TSHP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HBAR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 1619571658,
     'block_updated_at': '2021-04-28T01:05:07.195+00:00', 'block_elapsed_minutes': 5},
    {'currency': 'WIN', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 29709510,
     'block_updated_at': '2021-04-28T01:07:16.576+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MED', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 6454600,
     'block_updated_at': '2021-04-28T01:07:24.078+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MLK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 58939833,
     'block_updated_at': '2021-04-28T01:07:24.316+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CHZ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HIVE', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 53408408,
     'block_updated_at': '2021-04-28T01:07:21.496+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HBD', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 53408408,
     'block_updated_at': '2021-04-28T01:07:21.496+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XPR', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'OGN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ITAM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'OBSR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DKA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STMX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'AHT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 58939831,
     'block_updated_at': '2021-04-28T01:07:22.753+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PCI', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 16212960,
     'block_updated_at': '2021-04-28T01:07:19.589+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'KAVA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 256402,
     'block_updated_at': '2021-04-28T01:07:23.364+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RINGX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LINK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'JST', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 29709510,
     'block_updated_at': '2021-04-28T01:07:16.576+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RVC', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 1725176,
     'block_updated_at': '2021-04-28T01:07:22.520+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DAD', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'TON', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CTSI', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DOT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 4823597,
     'block_updated_at': '2021-04-28T01:07:23.018+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ONIT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'COMP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SXP', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HUNT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CRV', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ALGO', 'wallet_state': 'paused', 'block_state': 'inactive', 'block_height': 13478090,
     'block_updated_at': '2021-04-28T01:07:23.142+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'RSR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'OXT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MARO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 21172287,
     'block_updated_at': '2021-04-28T01:07:22.373+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SAND', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SUN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 29709510,
     'block_updated_at': '2021-04-28T01:07:16.576+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MVL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SRM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'QTCON', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'GXC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 40212030,
     'block_updated_at': '2021-04-28T01:07:24.168+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'AQT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'AXS', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STRAX', 'wallet_state': 'unsupported', 'block_state': 'normal', 'block_height': 315614,
     'block_updated_at': '2021-04-28T01:05:58.432+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'BCHA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 683954,
     'block_updated_at': '2021-04-28T01:03:45.214+00:00', 'block_elapsed_minutes': 7},
    {'currency': 'GLM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'FCT2', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SSX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 57868828,
     'block_updated_at': '2021-04-28T01:07:24.910+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'XYM', 'wallet_state': 'unsupported', 'block_state': None, 'block_height': None,
     'block_updated_at': None, 'block_elapsed_minutes': None},
    {'currency': 'FIL', 'wallet_state': 'paused', 'block_state': 'normal', 'block_height': 708845,
     'block_updated_at': '2021-04-28T01:05:10.579+00:00', 'block_elapsed_minutes': 5},
    {'currency': 'UNI', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BASIC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'INJ', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'VAL', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 3067550,
     'block_updated_at': '2021-04-28T01:06:10.727+00:00', 'block_elapsed_minutes': 4},
    {'currency': 'PSG', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 9779005,
     'block_updated_at': '2021-04-28T01:07:20.977+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'JUV', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 9779005,
     'block_updated_at': '2021-04-28T01:07:20.977+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CBK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'ONX', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'MIR', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'FOR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'BFC', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LINA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'HUM', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STX', 'wallet_state': 'working', 'block_state': 'delayed', 'block_height': 12698,
     'block_updated_at': '2021-04-28T01:04:35.465+00:00', 'block_elapsed_minutes': 6},
    {'currency': 'PICA', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'CELO', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 6399099,
     'block_updated_at': '2021-04-28T01:07:23.048+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'GRT', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'LZM', 'wallet_state': 'withdraw_only', 'block_state': 'normal', 'block_height': 58939833,
     'block_updated_at': '2021-04-28T01:07:24.316+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'AUCTION', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DON', 'wallet_state': 'withdraw_only', 'block_state': 'delayed', 'block_height': 134471950,
     'block_updated_at': '2021-04-28T01:07:21.034+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'NEAR', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 35913226,
     'block_updated_at': '2021-04-28T01:07:23.269+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'DAWN', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'FLOW', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 13935820,
     'block_updated_at': '2021-04-28T01:07:10.313+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'PUNDIX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'STRK', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3},
    {'currency': 'SNX', 'wallet_state': 'working', 'block_state': 'normal', 'block_height': 12325840,
     'block_updated_at': '2021-04-28T01:07:06.167+00:00', 'block_elapsed_minutes': 3}
]


