bits_name_list = [
    {'market': 'KRW-BTC', 'korean_name': '비트코인', 'english_name': 'Bitcoin'},
    {'market': 'BTC-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum'},
    {'market': 'BTC-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin'},
    {'market': 'BTC-XRP', 'korean_name': '리플', 'english_name': 'Ripple'},
    {'market': 'BTC-ETC',
     'korean_name': '이더리움클래식',
     'english_name': 'Ethereum Classic'},
    {'market': 'BTC-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo'},
    {'market': 'BTC-CVC', 'korean_name': '시빅', 'english_name': 'Civic'},
    {'market': 'BTC-DGB', 'korean_name': '디지바이트', 'english_name': 'DigiByte'},
    {'market': 'BTC-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin'},
    {'market': 'BTC-SNT',
     'korean_name': '스테이터스네트워크토큰',
     'english_name': 'Status Network Token'},
    {'market': 'BTC-WAVES', 'korean_name': '웨이브', 'english_name': 'Waves'},
    {'market': 'BTC-NMR', 'korean_name': '뉴메레르', 'english_name': 'Numeraire'},
    {'market': 'BTC-XEM', 'korean_name': '넴', 'english_name': 'NEM'},
    {'market': 'BTC-LBC',
     'korean_name': '엘비알와이크레딧',
     'english_name': 'LBRY Credits'},
    {'market': 'BTC-QTUM', 'korean_name': '퀀텀', 'english_name': 'Qtum'},
    {'market': 'BTC-NXT', 'korean_name': '엔엑스티', 'english_name': 'Nxt'},
    {'market': 'BTC-BAT',
     'korean_name': '베이직어텐션토큰',
     'english_name': 'Basic Attention Token'},
    {'market': 'BTC-LSK', 'korean_name': '리스크', 'english_name': 'Lisk'},
    {'market': 'BTC-RDD', 'korean_name': '레드코인', 'english_name': 'ReddCoin'},
    {'market': 'BTC-STEEM', 'korean_name': '스팀', 'english_name': 'Steem'},
    {'market': 'BTC-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin'},
    {'market': 'BTC-BNT', 'korean_name': '뱅코르', 'english_name': 'Bancor'},
    {'market': 'BTC-XLM', 'korean_name': '스텔라루멘', 'english_name': 'Lumen'},
    {'market': 'BTC-ARDR', 'korean_name': '아더', 'english_name': 'Ardor'},
    {'market': 'BTC-KMD', 'korean_name': '코모도', 'english_name': 'Komodo'},
    {'market': 'BTC-ARK', 'korean_name': '아크', 'english_name': 'Ark'},
    {'market': 'BTC-ADX', 'korean_name': '애드엑스', 'english_name': 'AdEx'},
    {'market': 'BTC-SYS', 'korean_name': '시스코인', 'english_name': 'SysCoin'},
    {'market': 'BTC-ANT', 'korean_name': '아라곤', 'english_name': 'Aragon'},
    {'market': 'BTC-STORJ', 'korean_name': '스토리지', 'english_name': 'Storj'},
    {'market': 'BTC-GRS', 'korean_name': '그로스톨코인', 'english_name': 'Groestlcoin'},
    {'market': 'BTC-REP', 'korean_name': '어거', 'english_name': 'Augur'},
    {'market': 'BTC-RLC', 'korean_name': '아이젝', 'english_name': 'iEx.ec'},
    {'market': 'BTC-EMC2',
     'korean_name': '아인스타이늄',
     'english_name': 'Einsteinium'},
    {'market': 'BTC-ADA', 'korean_name': '에이다', 'english_name': 'Ada'},
    {'market': 'BTC-MANA',
     'korean_name': '디센트럴랜드',
     'english_name': 'Decentraland'},
    {'market': 'BTC-SBD', 'korean_name': '스팀달러', 'english_name': 'SteemDollars'},
    {'market': 'BTC-RCN',
     'korean_name': '리피오크레딧네트워크',
     'english_name': 'Ripio Credit Network'},
    {'market': 'BTC-POWR', 'korean_name': '파워렛저', 'english_name': 'Power ledger'},
    {'market': 'BTC-DNT', 'korean_name': '디스트릭트0x', 'english_name': 'district0x'},
    {'market': 'BTC-IGNIS', 'korean_name': '이그니스', 'english_name': 'Ignis'},
    {'market': 'BTC-ZRX', 'korean_name': '제로엑스', 'english_name': '0x Protocol'},
    {'market': 'BTC-TRX', 'korean_name': '트론', 'english_name': 'TRON'},
    {'market': 'BTC-TUSD', 'korean_name': '트루USD', 'english_name': 'TrueUSD'},
    {'market': 'BTC-LRC', 'korean_name': '루프링', 'english_name': 'Loopring'},
    {'market': 'BTC-DMT', 'korean_name': '디마켓', 'english_name': 'DMarket'},
    {'market': 'BTC-POLY', 'korean_name': '폴리매쓰', 'english_name': 'Polymath'},
    {'market': 'BTC-PRO', 'korean_name': '프로피', 'english_name': 'Propy'},
    {'market': 'BTC-BCH',
     'korean_name': '비트코인캐시',
     'english_name': 'Bitcoin Cash'},
    {'market': 'BTC-MFT', 'korean_name': '메인프레임', 'english_name': 'Mainframe'},
    {'market': 'BTC-LOOM',
     'korean_name': '룸네트워크',
     'english_name': 'Loom Network'},
    {'market': 'BTC-RFR', 'korean_name': '리퍼리움', 'english_name': 'Refereum'},
    {'market': 'BTC-RVN', 'korean_name': '레이븐코인', 'english_name': 'Ravencoin'},
    {'market': 'BTC-BFT',
     'korean_name': '비에프토큰',
     'english_name': 'BnkToTheFuture'},
    {'market': 'BTC-GO', 'korean_name': '고체인', 'english_name': 'GoChain'},
    {'market': 'BTC-UPP',
     'korean_name': '센티넬프로토콜',
     'english_name': 'Sentinel Protocol'},
    {'market': 'BTC-ENJ', 'korean_name': '엔진코인', 'english_name': 'Enjin'},
    {'market': 'BTC-EDR', 'korean_name': '엔도르', 'english_name': 'Endor'},
    {'market': 'BTC-MTL', 'korean_name': '메탈', 'english_name': 'Metal'},
    {'market': 'BTC-PAX',
     'korean_name': '팩소스스탠다드',
     'english_name': 'Paxos Standard'},
    {'market': 'BTC-MOC', 'korean_name': '모스코인', 'english_name': 'Moss Coin'},
    {'market': 'BTC-ZIL', 'korean_name': '질리카', 'english_name': 'Zilliqa'},
    {'market': 'BTC-BSV',
     'korean_name': '비트코인에스브이',
     'english_name': 'Bitcoin SV'},
    {'market': 'BTC-IOST', 'korean_name': '아이오에스티', 'english_name': 'IOST'},
    {'market': 'BTC-NCASH',
     'korean_name': '뉴클리어스비전',
     'english_name': 'Nucleus Vision'},
    {'market': 'BTC-DENT', 'korean_name': '덴트', 'english_name': 'Dent'},
    {'market': 'BTC-ELF', 'korean_name': '엘프', 'english_name': 'aelf'},
    {'market': 'BTC-BTT', 'korean_name': '비트토렌트', 'english_name': 'BitTorrent'},
    {'market': 'BTC-VITE', 'korean_name': '비트토큰', 'english_name': 'Vite'},
    {'market': 'BTC-IOTX', 'korean_name': '아이오텍스', 'english_name': 'IoTeX'},
    {'market': 'BTC-SOLVE', 'korean_name': '솔브케어', 'english_name': 'Solve.Care'},
    {'market': 'BTC-NKN', 'korean_name': '엔케이엔', 'english_name': 'NKN'},
    {'market': 'BTC-META', 'korean_name': '메타디움', 'english_name': 'Metadium'},
    {'market': 'BTC-ANKR', 'korean_name': '앵커', 'english_name': 'Ankr'},
    {'market': 'BTC-CRO',
     'korean_name': '크립토닷컴체인',
     'english_name': 'Crypto.com Chain'},
    {'market': 'BTC-FSN', 'korean_name': '퓨전', 'english_name': 'Fusion'},
    {'market': 'BTC-ORBS', 'korean_name': '오브스', 'english_name': 'Orbs'},
    {'market': 'BTC-AERGO', 'korean_name': '아르고', 'english_name': 'Aergo'},
    {'market': 'BTC-PI', 'korean_name': '플리안', 'english_name': 'Plian'},
    {'market': 'BTC-ATOM', 'korean_name': '코스모스', 'english_name': 'Cosmos'},
    {'market': 'BTC-STPT',
     'korean_name': '에스티피',
     'english_name': 'Standard Tokenization Protocol'},
    {'market': 'BTC-LAMB', 'korean_name': '람다', 'english_name': 'Lambda'},
    {'market': 'BTC-EOS', 'korean_name': '이오스', 'english_name': 'EOS'},
    {'market': 'BTC-LUNA', 'korean_name': '루나', 'english_name': 'Luna'},
    {'market': 'BTC-DAI', 'korean_name': '다이', 'english_name': 'Dai'},
    {'market': 'BTC-MKR', 'korean_name': '메이커', 'english_name': 'Maker'},
    {'market': 'BTC-BORA', 'korean_name': '보라', 'english_name': 'BORA'},
    {'market': 'BTC-TSHP', 'korean_name': '트웰브쉽스', 'english_name': '12SHIPS'},
    {'market': 'BTC-WAXP', 'korean_name': '왁스', 'english_name': 'WAX'},
    {'market': 'BTC-MED', 'korean_name': '메디블록', 'english_name': 'MediBloc'},
    {'market': 'BTC-MLK', 'korean_name': '밀크', 'english_name': 'MiL.k'},
    {'market': 'BTC-PXL', 'korean_name': '픽셀', 'english_name': 'PIXEL'},
    {'market': 'BTC-VET', 'korean_name': '비체인', 'english_name': 'VeChain'},
    {'market': 'BTC-CHZ', 'korean_name': '칠리즈', 'english_name': 'Chiliz'},
    {'market': 'BTC-FX', 'korean_name': '펑션엑스', 'english_name': 'Function X'},
    {'market': 'BTC-OGN',
     'korean_name': '오리진프로토콜',
     'english_name': 'Origin Protocol'},
    {'market': 'BTC-ITAM', 'korean_name': '아이텀', 'english_name': 'ITAM'},
    {'market': 'BTC-XTZ', 'korean_name': '테조스', 'english_name': 'Tezos'},
    {'market': 'BTC-HIVE', 'korean_name': '하이브', 'english_name': 'Hive'},
    {'market': 'BTC-HBD', 'korean_name': '하이브달러', 'english_name': 'Hive Dollar'},
    {'market': 'BTC-OBSR', 'korean_name': '옵저버', 'english_name': 'Observer'},
    {'market': 'BTC-DKA', 'korean_name': '디카르고', 'english_name': 'dKargo'},
    {'market': 'BTC-STMX', 'korean_name': '스톰엑스', 'english_name': 'StormX'},
    {'market': 'BTC-AHT', 'korean_name': '아하토큰', 'english_name': 'AhaToken'},
    {'market': 'BTC-PCI', 'korean_name': '페이코인', 'english_name': 'PayCoin'},
    {'market': 'BTC-RINGX', 'korean_name': '링엑스', 'english_name': 'RINGX'},
    {'market': 'BTC-LINK', 'korean_name': '체인링크', 'english_name': 'Chainlink'},
    {'market': 'BTC-KAVA', 'korean_name': '카바', 'english_name': 'Kava'},
    {'market': 'BTC-JST', 'korean_name': '저스트', 'english_name': 'JUST'},
    {'market': 'BTC-CHR', 'korean_name': '크로미아', 'english_name': 'Chromia'},
    {'market': 'BTC-DAD', 'korean_name': '다드', 'english_name': 'DAD'},
    {'market': 'BTC-TON', 'korean_name': '톤', 'english_name': 'TON'},
    {'market': 'BTC-CTSI', 'korean_name': '카르테시', 'english_name': 'Cartesi'},
    {'market': 'BTC-DOT', 'korean_name': '폴카닷', 'english_name': 'Polkadot'},
    {'market': 'BTC-COMP', 'korean_name': '컴파운드', 'english_name': 'Compound'},
    {'market': 'BTC-SXP', 'korean_name': '스와이프', 'english_name': 'Swipe'},
    {'market': 'BTC-HUNT', 'korean_name': '헌트', 'english_name': 'HUNT'},
    {'market': 'BTC-ONIT', 'korean_name': '온버프', 'english_name': 'ONBUFF'},
    {'market': 'BTC-CRV', 'korean_name': '커브', 'english_name': 'Curve'},
    {'market': 'BTC-ALGO', 'korean_name': '알고랜드', 'english_name': 'Algorand'},
    {'market': 'BTC-RSR',
     'korean_name': '리저브라이트',
     'english_name': 'Reserve Rights'},
    {'market': 'BTC-OXT', 'korean_name': '오키드', 'english_name': 'Orchid'},
    {'market': 'BTC-PLA', 'korean_name': '플레이댑', 'english_name': 'PlayDapp'},
    {'market': 'BTC-MARO', 'korean_name': '마로', 'english_name': 'Maro'},
    {'market': 'BTC-SAND', 'korean_name': '샌드박스', 'english_name': 'The Sandbox'},
    {'market': 'BTC-SUN', 'korean_name': '썬', 'english_name': 'SUN'},
    {'market': 'BTC-SRM', 'korean_name': '세럼', 'english_name': 'Serum'},
    {'market': 'BTC-QTCON', 'korean_name': '퀴즈톡', 'english_name': 'Quiztok'},
    {'market': 'BTC-MVL', 'korean_name': '엠블', 'english_name': 'MVL'},
    {'market': 'BTC-GXC', 'korean_name': '지엑스체인', 'english_name': 'GXChain'},
    {'market': 'BTC-AQT',
     'korean_name': '알파쿼크',
     'english_name': 'Alpha Quark Token'},
    {'market': 'BTC-AXS',
     'korean_name': '엑시인피니티',
     'english_name': 'Axie Infinity'},
    {'market': 'BTC-STRAX', 'korean_name': '스트라티스', 'english_name': 'Stratis'},
    {'market': 'BTC-BCHA',
     'korean_name': '비트코인캐시에이비씨',
     'english_name': 'Bitcoin Cash ABC'},
    {'market': 'BTC-GLM', 'korean_name': '골렘', 'english_name': 'Golem'},
    {'market': 'BTC-FCT2', 'korean_name': '피르마체인', 'english_name': 'FirmaChain'},
    {'market': 'BTC-SSX', 'korean_name': '썸씽', 'english_name': 'SOMESING'},
    {'market': 'BTC-FIL', 'korean_name': '파일코인', 'english_name': 'Filecoin'},
    {'market': 'BTC-UNI', 'korean_name': '유니스왑', 'english_name': 'Uniswap'},
    {'market': 'BTC-BASIC', 'korean_name': '베이직', 'english_name': 'Basic'},
    {'market': 'BTC-INJ',
     'korean_name': '인젝티브프로토콜',
     'english_name': 'Injective Protocol'},
    {'market': 'BTC-PROM', 'korean_name': '프로메테우스', 'english_name': 'Prometeus'},
    {'market': 'BTC-VAL', 'korean_name': '밸리디티', 'english_name': 'Validity'},
    {'market': 'BTC-PSG',
     'korean_name': '파리생제르맹',
     'english_name': 'Paris Saint-Germain Fan Token'},
    {'market': 'BTC-JUV',
     'korean_name': '유벤투스',
     'english_name': 'Juventus Fan Token'},
    {'market': 'BTC-CBK', 'korean_name': '코박토큰', 'english_name': 'Cobak Token'},
    {'market': 'BTC-FOR', 'korean_name': '포튜브', 'english_name': 'ForTube'},
    {'market': 'BTC-BFC', 'korean_name': '바이프로스트', 'english_name': 'Bifrost'},
    {'market': 'BTC-LINA', 'korean_name': '리니어파이낸스', 'english_name': 'Linear'},
    {'market': 'BTC-HUM', 'korean_name': '휴먼스케이프', 'english_name': 'Humanscape'},
    {'market': 'BTC-PICA', 'korean_name': '피카', 'english_name': 'Pica'},
    {'market': 'BTC-CELO', 'korean_name': '셀로', 'english_name': 'Celo'},
    {'market': 'BTC-IQ', 'korean_name': '에브리피디아', 'english_name': 'Everipedia'},
    {'market': 'BTC-STX', 'korean_name': '스택스', 'english_name': 'Stacks'},
    {'market': 'BTC-NEAR',
     'korean_name': '니어프로토콜',
     'english_name': 'NEAR Protocol'},
    {'market': 'BTC-AUCTION', 'korean_name': '바운스토큰', 'english_name': 'Bounce'},
    {'market': 'BTC-DAWN',
     'korean_name': '던프로토콜',
     'english_name': 'Dawn Protocol'},
    {'market': 'BTC-FLOW', 'korean_name': '플로우', 'english_name': 'Flow'},
    {'market': 'BTC-STRK', 'korean_name': '스트라이크', 'english_name': 'Strike'},
    {'market': 'BTC-PUNDIX', 'korean_name': '펀디엑스', 'english_name': 'Pundi X'}
]

market_withdraw_fee_info = {
    'ADA': {'업비트최소출금금액': 0, '업비트출금수수료': 0.5, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'ADX': {'업비트최소출금금액': 0,
            '업비트출금수수료': 14.0,
            '바이낸스최소출금금액': 30.0,
            '바이낸스출금수수료': 15.0},
    'AERGO': {'업비트최소출금금액': 0,
              '업비트출금수수료': 50.0,
              '바이낸스최소출금금액': 112.0,
              '바이낸스출금수수료': 56.0},
    'ALGO': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.1,
             '바이낸스최소출금금액': 10.0,
             '바이낸스출금수수료': 0.01},
    'ANKR': {'업비트최소출금금액': 0,
             '업비트출금수수료': 150.0,
             '바이낸스최소출금금액': 276.0,
             '바이낸스출금수수료': 138.0},
    'ANT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 1.5,
            '바이낸스최소출금금액': 3.3,
            '바이낸스출금수수료': 1.65},
    'ARDR': {'업비트최소출금금액': 0,
             '업비트출금수수료': 2.0,
             '바이낸스최소출금금액': 4.0,
             '바이낸스출금수수료': 2.0},
    'ARK': {'업비트최소출금금액': 0, '업비트출금수수료': 0.1, '바이낸스최소출금금액': 0.4, '바이낸스출금수수료': 0.2},
    'ATOM': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.01,
             '바이낸스최소출금금액': 0.01,
             '바이낸스출금수수료': 0.005},
    'AUCTION': {'업비트최소출금금액': 0,
                '업비트출금수수료': 0.4,
                '바이낸스최소출금금액': 1.08,
                '바이낸스출금수수료': 0.54},
    'AXS': {'업비트최소출금금액': 0,
            '업비트출금수수료': 3.0,
            '바이낸스최소출금금액': 4.92,
            '바이낸스출금수수료': 2.46},
    'BAT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 20.0,
            '바이낸스최소출금금액': 34.0,
            '바이낸스출금수수료': 17.0},
    'BCH': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.001,
            '바이낸스최소출금금액': 0.002,
            '바이낸스출금수수료': 0.001},
    'BCHA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.001,
             '바이낸스최소출금금액': 0.005,
             '바이낸스출금수수료': 0.001},
    'BNT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 3.0,
            '바이낸스최소출금금액': 5.52,
            '바이낸스출금수수료': 2.76},
    'BTC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0009,
            '바이낸스최소출금금액': 0.001,
            '바이낸스출금수수료': 0.0005},
    'BTG': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.001,
            '바이낸스최소출금금액': 0.002,
            '바이낸스출금수수료': 0.001},
    'BTM': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.1,
            '바이낸스최소출금금액': 10.0,
            '바이낸스출금수수료': 5.0},
    'BTS': {'업비트최소출금금액': 0, '업비트출금수수료': 5.0, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'BTT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0,
            '바이낸스최소출금금액': 26.0,
            '바이낸스출금수수료': 13.0},
    'CBK': {'업비트최소출금금액': 0, '업비트출금수수료': 1.0, '바이낸스최소출금금액': 2.4, '바이낸스출금수수료': 1.2},
    'CELO': {'업비트최소출금금액': 0,
             '업비트출금수수료': 2.0,
             '바이낸스최소출금금액': 0.002,
             '바이낸스출금수수료': 0.001},
    'CHZ': {'업비트최소출금금액': 0,
            '업비트출금수수료': 50.0,
            '바이낸스최소출금금액': 92.0,
            '바이낸스출금수수료': 46.0},
    'CLOAK': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.02,
              '바이낸스최소출금금액': 0.02,
              '바이낸스출금수수료': 0.02},
    'COMP': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.04,
             '바이낸스최소출금금액': 0.082,
             '바이낸스출금수수료': 0.041},
    'CRV': {'업비트최소출금금액': 0,
            '업비트출금수수료': 5.0,
            '바이낸스최소출금금액': 12.0,
            '바이낸스출금수수료': 6.34},
    'CTSI': {'업비트최소출금금액': 0,
             '업비트출금수수료': 45.0,
             '바이낸스최소출금금액': 74.0,
             '바이낸스출금수수료': 37.0},
    'CVC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 30.0,
            '바이낸스최소출금금액': 70.0,
            '바이낸스출금수수료': 35.0},
    'DAI': {'업비트최소출금금액': 0,
            '업비트출금수수료': 15.0,
            '바이낸스최소출금금액': 30.0,
            '바이낸스출금수수료': 15.0},
    'DASH': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.002,
             '바이낸스최소출금금액': 0.004,
             '바이낸스출금수수료': 0.002},
    'DCR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.05,
            '바이낸스최소출금금액': 0.02,
            '바이낸스출금수수료': 0.01},
    'DENT': {'업비트최소출금금액': 0,
             '업비트출금수수료': 1500.0,
             '바이낸스최소출금금액': 2222.0,
             '바이낸스출금수수료': 1111.0},
    'DGB': {'업비트최소출금금액': 0, '업비트출금수수료': 0.2, '바이낸스최소출금금액': 0.4, '바이낸스출금수수료': 0.2},
    'DNT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 60.0,
            '바이낸스최소출금금액': 334.0,
            '바이낸스출금수수료': 167.0},
    'DOGE': {'업비트최소출금금액': 0,
             '업비트출금수수료': 2.0,
             '바이낸스최소출금금액': 100.0,
             '바이낸스출금수수료': 20.0},
    'DON': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0,
            '바이낸스최소출금금액': 0.022,
            '바이낸스출금수수료': 0.011},
    'DOT': {'업비트최소출금금액': 0, '업비트출금수수료': 1.5, '바이낸스최소출금금액': 3.0, '바이낸스출금수수료': 0.1},
    'ELF': {'업비트최소출금금액': 0,
            '업비트출금수수료': 40.0,
            '바이낸스최소출금금액': 92.0,
            '바이낸스출금수수료': 46.0},
    'ENG': {'업비트최소출금금액': 0, '업비트출금수수료': 1.5, '바이낸스최소출금금액': 1.0, '바이낸스출금수수료': 0.0},
    'ENJ': {'업비트최소출금금액': 0,
            '업비트출금수수료': 13.0,
            '바이낸스최소출금금액': 17.0,
            '바이낸스출금수수료': 8.9},
    'EOS': {'업비트최소출금금액': 0, '업비트출금수수료': 0.0, '바이낸스최소출금금액': 0.2, '바이낸스출금수수료': 0.1},
    'ETC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 0.02,
            '바이낸스출금수수료': 0.01},
    'ETH': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.018,
            '바이낸스최소출금금액': 0.016,
            '바이낸스출금수수료': 0.008},
    'FIL': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.15,
            '바이낸스최소출금금액': 0.01,
            '바이낸스출금수수료': 0.001},
    'FOR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 200.0,
            '바이낸스최소출금금액': 508.0,
            '바이낸스출금수수료': 254.0},
    'FUN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 60.0,
            '바이낸스최소출금금액': 820.0,
            '바이낸스출금수수료': 410.0},
    'GAS': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0,
            '바이낸스최소출금금액': 1.0,
            '바이낸스출금수수료': 0.005},
    'GLM': {'업비트최소출금금액': 0,
            '업비트출금수수료': 25.0,
            '바이낸스최소출금금액': 76.0,
            '바이낸스출금수수료': 38.0},
    'GO': {'업비트최소출금금액': 0, '업비트출금수수료': 0.01, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'GRS': {'업비트최소출금금액': 0, '업비트출금수수료': 0.2, '바이낸스최소출금금액': 0.4, '바이낸스출금수수료': 0.2},
    'HBAR': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.01,
             '바이낸스최소출금금액': 2.0,
             '바이낸스출금수수료': 1.0},
    'ICX': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 0.04,
            '바이낸스출금수수료': 0.02},
    'INJ': {'업비트최소출금금액': 0, '업비트출금수수료': 1.2, '바이낸스최소출금금액': 3.2, '바이낸스출금수수료': 1.6},
    'IOST': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.0,
             '바이낸스최소출금금액': 2.0,
             '바이낸스출금수수료': 1.0},
    'IOTA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.0,
             '바이낸스최소출금금액': 1.0,
             '바이낸스출금수수료': 0.5},
    'IOTX': {'업비트최소출금금액': 0,
             '업비트출금수수료': 110.0,
             '바이낸스최소출금금액': 1.0,
             '바이낸스출금수수료': 0.1},
    'IQ': {'업비트최소출금금액': 0,
           '업비트출금수수료': 0.0,
           '바이낸스최소출금금액': 100.0,
           '바이낸스출금수수료': 50.0},
    'JST': {'업비트최소출금금액': 0,
            '업비트출금수수료': 30.0,
            '바이낸스최소출금금액': 100.0,
            '바이낸스출금수수료': 50.0},
    'KAVA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 1.7,
             '바이낸스최소출금금액': 0.1,
             '바이낸스출금수수료': 0.001},
    'KMD': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.002,
            '바이낸스최소출금금액': 0.004,
            '바이낸스출금수수료': 0.002},
    'KNC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 7.0,
            '바이낸스최소출금금액': 12.0,
            '바이낸스출금수수료': 6.46},
    'LINA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 200.0,
             '바이낸스최소출금금액': 390.0,
             '바이낸스출금수수료': 195.0},
    'LINK': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.6,
             '바이낸스최소출금금액': 1.32,
             '바이낸스출금수수료': 0.66},
    'LOOM': {'업비트최소출금금액': 0,
             '업비트출금수수료': 90.0,
             '바이낸스최소출금금액': 210.0,
             '바이낸스출금수수료': 105.0},
    'LRC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 30.0,
            '바이낸스최소출금금액': 70.0,
            '바이낸스출금수수료': 35.0},
    'LSK': {'업비트최소출금금액': 0, '업비트출금수수료': 0.1, '바이낸스최소출금금액': 0.2, '바이낸스출금수수료': 0.1},
    'LTC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 0.002,
            '바이낸스출금수수료': 0.001},
    'LUN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.5,
            '바이낸스최소출금금액': 3.08,
            '바이낸스출금수수료': 1.54},
    'LUNA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.01,
             '바이낸스최소출금금액': 5.0,
             '바이낸스출금수수료': 0.02},
    'MANA': {'업비트최소출금금액': 0,
             '업비트출금수수료': 35.0,
             '바이낸스최소출금금액': 42.0,
             '바이낸스출금수수료': 21.0},
    'MBL': {'업비트최소출금금액': 0,
            '업비트출금수수료': 600.0,
            '바이낸스최소출금금액': 7.68,
            '바이낸스출금수수료': 3.84},
    'MCO': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.5,
            '바이낸스최소출금금액': 2.82,
            '바이낸스출금수수료': 1.41},
    'MFT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 600.0,
            '바이낸스최소출금금액': 1624.0,
            '바이낸스출금수수료': 812.0},
    'MKR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.005,
            '바이낸스최소출금금액': 0.018,
            '바이낸스출금수수료': 0.0091},
    'MTL': {'업비트최소출금금액': 0,
            '업비트출금수수료': 3.0,
            '바이낸스최소출금금액': 7.94,
            '바이낸스출금수수료': 3.97},
    'NAV': {'업비트최소출금금액': 0, '업비트출금수수료': 0.2, '바이낸스최소출금금액': 0.4, '바이낸스출금수수료': 0.2},
    'NCASH': {'업비트최소출금금액': 0,
              '업비트출금수수료': 2200.0,
              '바이낸스최소출금금액': 4816.0,
              '바이낸스출금수수료': 2408.0},
    'NEAR': {'업비트최소출금금액': 0,
             '업비트출금수수료': 2.0,
             '바이낸스최소출금금액': 0.2,
             '바이낸스출금수수료': 0.01},
    'NEO': {'업비트최소출금금액': 0, '업비트출금수수료': 0.0, '바이낸스최소출금금액': 1.0, '바이낸스출금수수료': 0.0},
    'NKN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 50.0,
            '바이낸스최소출금금액': 76.0,
            '바이낸스출금수수료': 38.0},
    'NMR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.4,
            '바이낸스최소출금금액': 0.62,
            '바이낸스출금수수료': 0.31},
    'NXS': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.2,
            '바이낸스최소출금금액': 0.04,
            '바이낸스출금수수료': 0.02},
    'OGN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 10.0,
            '바이낸스최소출금금액': 16.0,
            '바이낸스출금수수료': 8.44},
    'OMG': {'업비트최소출금금액': 0,
            '업비트출금수수료': 2.5,
            '바이낸스최소출금금액': 5.1,
            '바이낸스출금수수료': 2.55},
    'ONG': {'업비트최소출금금액': 0,
            '업비트출금수수료': 1.0,
            '바이낸스최소출금금액': 0.17,
            '바이낸스출금수수료': 0.087},
    'ONT': {'업비트최소출금금액': 0, '업비트출금수수료': 0.5, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'ONX': {'업비트최소출금금액': 0,
            '업비트출금수수료': 2.0,
            '바이낸스최소출금금액': 10.0,
            '바이낸스출금수수료': 5.26},
    'OST': {'업비트최소출금금액': 0,
            '업비트출금수수료': 60.0,
            '바이낸스최소출금금액': 810.0,
            '바이낸스출금수수료': 405.0},
    'OXT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 25.0,
            '바이낸스최소출금금액': 50.0,
            '바이낸스출금수수료': 25.0},
    'PIVX': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.03,
             '바이낸스최소출금금액': 0.4,
             '바이낸스출금수수료': 0.2},
    'POLY': {'업비트최소출금금액': 0,
             '업비트출금수수료': 30.0,
             '바이낸스최소출금금액': 80.0,
             '바이낸스출금수수료': 40.0},
    'POWR': {'업비트최소출금금액': 0,
             '업비트출금수수료': 28.0,
             '바이낸스최소출금금액': 80.0,
             '바이낸스출금수수료': 40.0},
    'PROM': {'업비트최소출금금액': 0,
             '업비트출금수수료': 1.5,
             '바이낸스최소출금금액': 3.04,
             '바이낸스출금수수료': 1.52},
    'QKC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 988.0,
            '바이낸스출금수수료': 494.0},
    'QTUM': {'업비트최소출금금액': 0,
             '업비트출금수수료': 0.01,
             '바이낸스최소출금금액': 0.02,
             '바이낸스출금수수료': 0.01},
    'RCN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 110.0,
            '바이낸스최소출금금액': 262.0,
            '바이낸스출금수수료': 131.0},
    'REP': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.45,
            '바이낸스최소출금금액': 0.96,
            '바이낸스출금수수료': 0.48},
    'RLC': {'업비트최소출금금액': 0,
            '업비트출금수수료': 6.5,
            '바이낸스최소출금금액': 14.0,
            '바이낸스출금수수료': 7.15},
    'RSR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 214.0,
            '바이낸스최소출금금액': 496.0,
            '바이낸스출금수수료': 248.0},
    'RVN': {'업비트최소출금금액': 0, '업비트출금수수료': 0.1, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'SALT': {'업비트최소출금금액': 0,
             '업비트출금수수료': 1.0,
             '바이낸스최소출금금액': 10.4,
             '바이낸스출금수수료': 5.2},
    'SAND': {'업비트최소출금금액': 0,
             '업비트출금수수료': 30.0,
             '바이낸스최소출금금액': 64.0,
             '바이낸스출금수수료': 32.0},
    'SC': {'업비트최소출금금액': 0, '업비트출금수수료': 0.1, '바이낸스최소출금금액': 0.2, '바이낸스출금수수료': 0.1},
    'SNGLS': {'업비트최소출금금액': 0,
              '업비트출금수수료': 3.5,
              '바이낸스최소출금금액': 1110.0,
              '바이낸스출금수수료': 555.0},
    'SNT': {'업비트최소출금금액': 0,
            '업비트출금수수료': 130.0,
            '바이낸스최소출금금액': 240.0,
            '바이낸스출금수수료': 120.0},
    'SRM': {'업비트최소출금금액': 0,
            '업비트출금수수료': 3.0,
            '바이낸스최소출금금액': 6.94,
            '바이낸스출금수수료': 3.47},
    'STEEM': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.01,
              '바이낸스최소출금금액': 0.02,
              '바이낸스출금수수료': 0.01},
    'STMX': {'업비트최소출금금액': 0,
             '업비트출금수수료': 310.0,
             '바이낸스최소출금금액': 542.0,
             '바이낸스출금수수료': 271.0},
    'STORJ': {'업비트최소출금금액': 0,
              '업비트출금수수료': 5.0,
              '바이낸스최소출금금액': 15.0,
              '바이낸스출금수수료': 7.65},
    'STPT': {'업비트최소출금금액': 0,
             '업비트출금수수료': 250.0,
             '바이낸스최소출금금액': 442.0,
             '바이낸스출금수수료': 221.0},
    'STRAX': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.2,
              '바이낸스최소출금금액': 0.2,
              '바이낸스출금수수료': 0.1},
    'STX': {'업비트최소출금금액': 0,
            '업비트출금수수료': 10.0,
            '바이낸스최소출금금액': 20.0,
            '바이낸스출금수수료': 1.0},
    'SUN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0018,
            '바이낸스최소출금금액': 0.0058,
            '바이낸스출금수수료': 0.0029},
    'SXP': {'업비트최소출금금액': 0,
            '업비트출금수수료': 5.0,
            '바이낸스최소출금금액': 9.46,
            '바이낸스출금수수료': 4.73},
    'SYS': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.0002,
            '바이낸스최소출금금액': 2.0,
            '바이낸스출금수수료': 1.0},
    'TFUEL': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.0,
              '바이낸스최소출금금액': 6.34,
              '바이낸스출금수수료': 3.17},
    'THETA': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.0,
              '바이낸스최소출금금액': 0.2,
              '바이낸스출금수수료': 0.1},
    'TRX': {'업비트최소출금금액': 0, '업비트출금수수료': 0.0, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'UNI': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.6,
            '바이낸스최소출금금액': 1.38,
            '바이낸스출금수수료': 0.69},
    'VET': {'업비트최소출금금액': 0,
            '업비트출금수수료': 100.0,
            '바이낸스최소출금금액': 200.0,
            '바이낸스출금수수료': 100.0},
    'VIA': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.2,
            '바이낸스최소출금금액': 0.02,
            '바이낸스출금수수료': 0.01},
    'VIB': {'업비트최소출금금액': 0,
            '업비트출금수수료': 17.0,
            '바이낸스최소출금금액': 348.0,
            '바이낸스출금수수료': 174.0},
    'VITE': {'업비트최소출금금액': 0,
             '업비트출금수수료': 30.0,
             '바이낸스최소출금금액': 2.0,
             '바이낸스출금수수료': 1.0},
    'VTHO': {'업비트최소출금금액': 0,
             '업비트출금수수료': 100.0,
             '바이낸스최소출금금액': 400.0,
             '바이낸스출금수수료': 200.0},
    'WAVES': {'업비트최소출금금액': 0,
              '업비트출금수수료': 0.001,
              '바이낸스최소출금금액': 0.004,
              '바이낸스출금수수료': 0.002},
    'WINGS': {'업비트최소출금금액': 0,
              '업비트출금수수료': 6.0,
              '바이낸스최소출금금액': 40.0,
              '바이낸스출금수수료': 20.0},
    'XEM': {'업비트최소출금금액': 0, '업비트출금수수료': 4.0, '바이낸스최소출금금액': 8.0, '바이낸스출금수수료': 4.0},
    'XLM': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 1.0,
            '바이낸스출금수수료': 0.02},
    'XMR': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.04,
            '바이낸스최소출금금액': 0.0002,
            '바이낸스출금수수료': 0.0001},
    'XPR': {'업비트최소출금금액': 0, '업비트출금수수료': 5.0, '바이낸스최소출금금액': 2.0, '바이낸스출금수수료': 1.0},
    'XRP': {'업비트최소출금금액': 0,
            '업비트출금수수료': 1.0,
            '바이낸스최소출금금액': 0.5,
            '바이낸스출금수수료': 0.25},
    'XTZ': {'업비트최소출금금액': 0, '업비트출금수수료': 0.1, '바이낸스최소출금금액': 1.0, '바이낸스출금수수료': 0.1},
    'XVG': {'업비트최소출금금액': 0, '업비트출금수수료': 0.2, '바이낸스최소출금금액': 0.2, '바이낸스출금수수료': 0.1},
    'ZEN': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.002,
            '바이낸스최소출금금액': 0.004,
            '바이낸스출금수수료': 0.002},
    'ZIL': {'업비트최소출금금액': 0,
            '업비트출금수수료': 0.01,
            '바이낸스최소출금금액': 0.02,
            '바이낸스출금수수료': 0.01},
    'ZRX': {'업비트최소출금금액': 0,
            '업비트출금수수료': 10.0,
            '바이낸스최소출금금액': 24.0,
            '바이낸스출금수수료': 12.0}
}
selected_coins = [
    'ADA',
     'ADX',
     'AERGO',
     'ALGO',
     'ANKR',
     'ANT',
     'ARDR',
     'ARK',
     'ATOM',
     'AUCTION',
     'AXS',
     'BAT',
     'BCH',
     'BNT',
     'CELO',
     'CHR',
     'CHZ',
     'COMP',
     'CRV',
     'CTSI',
     'CVC',
     'DGB',
     'DNT',
     'DOGE',
     'DOT',
     'ELF',
     'ENJ',
     'EOS',
     'ETC',
     'ETH',
     'FIL',
     'FOR',
     'GLM',
     'GO',
     'GRS',
     'GRT',
     'HIVE',
     'INJ',
     'IOST',
     'IOTX',
     'JST',
     'JUV',
     'KAVA',
     'KMD',
     'LINA',
     'LINK',
     'LOOM',
     'LRC',
     'LSK',
     'LTC',
     'LUNA',
     'MANA',
     'MKR',
     'MTL',
     'NEAR',
     'NKN',
     'NMR',
     'OGN',
     'OMG',
     'OXT',
     'POLY',
     'POWR',
     'PSG',
     'QTUM',
     'RCN',
     'REP',
     'RLC',
     'RSR',
     'RVN',
     'SAND',
     'SC',
     'SNT',
     'SNX',
     'SRM',
     'STEEM',
     'STMX',
     'STORJ',
     'STPT',
     'STRAX',
     'STX',
     'SXP',
     'SYS',
     'TRX',
     'UNI',
     'VET',
     'VITE',
     'WAVES',
     'XLM',
     'XRP',
     'XTZ',
     'ZIL',
     'ZRX'
]
selected_coin_kind = {
    '0': 'GO',
    '1': 'LUNA',
    '2': 'DAI',
    '3': 'MKR',
    '4': 'VET',
    '5': 'CHZ',
    '6': 'EOS',
    '7': 'XTZ',
    '8': 'HIVE',
    '9': 'STMX',
    '10': 'LINK',
    '11': 'OGN',
    '12': 'KAVA',
    '13': 'ATOM',
    '14': 'ENJ',
    '15': 'MTL',
    '16': 'PAX',
    '17': 'ZIL',
    '18': 'BSV',
    '19': 'IOST',
    '20': 'NCASH',
    '21': 'DENT',
    '22': 'STPT',
    '23': 'ELF',
    '24': 'VITE',
    '25': 'IOTX',
    '26': 'NKN',
    '27': 'ANKR',
    '28': 'AERGO',
    '29': 'BTT',
    '30': 'JST',
    '31': 'STORJ',
    '32': 'GRS',
    '33': 'REP',
    '34': 'RLC',
    '35': 'ADA',
    '36': 'MANA',
    '37': 'RCN',
    '38': 'POWR',
    '39': 'DNT',
    '40': 'ANT',
    '41': 'TRX',
    '42': 'TUSD',
    '43': 'LRC',
    '44': 'POLY',
    '45': 'BCH',
    '46': 'MFT',
    '47': 'LOOM',
    '48': 'RVN',
    '49': 'ZRX',
    '50': 'SYS',
    '51': 'CHR',
    '52': 'ARK',
    '53': 'ETH',
    '54': 'LTC',
    '55': 'XRP',
    '56': 'ETC',
    '57': 'OMG',
    '58': 'CVC',
    '59': 'DGB',
    '60': 'SC',
    '61': 'SNT',
    '62': 'WAVES',
    '63': 'NMR',
    '64': 'XEM',
    '65': 'ADX',
    '66': 'QTUM',
    '67': 'BAT',
    '68': 'LSK',
    '69': 'STEEM',
    '70': 'DOGE',
    '71': 'BNT',
    '72': 'XLM',
    '73': 'ARDR',
    '74': 'KMD'}
