bits_name_list = [{'market': 'KRW-BTC', 'korean_name': '비트코인', 'english_name': 'Bitcoin'},
                  {'market': 'BTC-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum'},
                  {'market': 'BTC-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin'},
                  {'market': 'BTC-XRP', 'korean_name': '리플', 'english_name': 'Ripple'},
                  {'market': 'BTC-ETC',
                   'korean_name': '이더리움클래식',
                   'english_name': 'Ethereum Classic'},
                  {'market': 'BTC-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo'},
                  {'market': 'BTC-CVC', 'korean_name': '시빅', 'english_name': 'Civic'},
                  {'market': 'BTC-DGB', 'korean_name': '디지바이트', 'english_name': 'DigiByte'},
                  {'market': 'BTC-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin'},
                  {'market': 'BTC-SNT',
                   'korean_name': '스테이터스네트워크토큰',
                   'english_name': 'Status Network Token'},
                  {'market': 'BTC-WAVES', 'korean_name': '웨이브', 'english_name': 'Waves'},
                  {'market': 'BTC-NMR', 'korean_name': '뉴메레르', 'english_name': 'Numeraire'},
                  {'market': 'BTC-XEM', 'korean_name': '넴', 'english_name': 'NEM'},
                  {'market': 'BTC-LBC',
                   'korean_name': '엘비알와이크레딧',
                   'english_name': 'LBRY Credits'},
                  {'market': 'BTC-QTUM', 'korean_name': '퀀텀', 'english_name': 'Qtum'},
                  {'market': 'BTC-NXT', 'korean_name': '엔엑스티', 'english_name': 'Nxt'},
                  {'market': 'BTC-BAT',
                   'korean_name': '베이직어텐션토큰',
                   'english_name': 'Basic Attention Token'},
                  {'market': 'BTC-LSK', 'korean_name': '리스크', 'english_name': 'Lisk'},
                  {'market': 'BTC-RDD', 'korean_name': '레드코인', 'english_name': 'ReddCoin'},
                  {'market': 'BTC-STEEM', 'korean_name': '스팀', 'english_name': 'Steem'},
                  {'market': 'BTC-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin'},
                  {'market': 'BTC-BNT', 'korean_name': '뱅코르', 'english_name': 'Bancor'},
                  {'market': 'BTC-XLM', 'korean_name': '스텔라루멘', 'english_name': 'Lumen'},
                  {'market': 'BTC-ARDR', 'korean_name': '아더', 'english_name': 'Ardor'},
                  {'market': 'BTC-KMD', 'korean_name': '코모도', 'english_name': 'Komodo'},
                  {'market': 'BTC-ARK', 'korean_name': '아크', 'english_name': 'Ark'},
                  {'market': 'BTC-ADX', 'korean_name': '애드엑스', 'english_name': 'AdEx'},
                  {'market': 'BTC-SYS', 'korean_name': '시스코인', 'english_name': 'SysCoin'},
                  {'market': 'BTC-ANT', 'korean_name': '아라곤', 'english_name': 'Aragon'},
                  {'market': 'BTC-STORJ', 'korean_name': '스토리지', 'english_name': 'Storj'},
                  {'market': 'BTC-GRS', 'korean_name': '그로스톨코인', 'english_name': 'Groestlcoin'},
                  {'market': 'BTC-REP', 'korean_name': '어거', 'english_name': 'Augur'},
                  {'market': 'BTC-RLC', 'korean_name': '아이젝', 'english_name': 'iEx.ec'},
                  {'market': 'BTC-EMC2',
                   'korean_name': '아인스타이늄',
                   'english_name': 'Einsteinium'},
                  {'market': 'BTC-ADA', 'korean_name': '에이다', 'english_name': 'Ada'},
                  {'market': 'BTC-MANA',
                   'korean_name': '디센트럴랜드',
                   'english_name': 'Decentraland'},
                  {'market': 'BTC-SBD', 'korean_name': '스팀달러', 'english_name': 'SteemDollars'},
                  {'market': 'BTC-RCN',
                   'korean_name': '리피오크레딧네트워크',
                   'english_name': 'Ripio Credit Network'},
                  {'market': 'BTC-POWR', 'korean_name': '파워렛저', 'english_name': 'Power ledger'},
                  {'market': 'BTC-DNT', 'korean_name': '디스트릭트0x', 'english_name': 'district0x'},
                  {'market': 'BTC-IGNIS', 'korean_name': '이그니스', 'english_name': 'Ignis'},
                  {'market': 'BTC-ZRX', 'korean_name': '제로엑스', 'english_name': '0x Protocol'},
                  {'market': 'BTC-TRX', 'korean_name': '트론', 'english_name': 'TRON'},
                  {'market': 'BTC-TUSD', 'korean_name': '트루USD', 'english_name': 'TrueUSD'},
                  {'market': 'BTC-LRC', 'korean_name': '루프링', 'english_name': 'Loopring'},
                  {'market': 'BTC-DMT', 'korean_name': '디마켓', 'english_name': 'DMarket'},
                  {'market': 'BTC-POLY', 'korean_name': '폴리매쓰', 'english_name': 'Polymath'},
                  {'market': 'BTC-PRO', 'korean_name': '프로피', 'english_name': 'Propy'},
                  {'market': 'BTC-BCH',
                   'korean_name': '비트코인캐시',
                   'english_name': 'Bitcoin Cash'},
                  {'market': 'BTC-MFT', 'korean_name': '메인프레임', 'english_name': 'Mainframe'},
                  {'market': 'BTC-LOOM',
                   'korean_name': '룸네트워크',
                   'english_name': 'Loom Network'},
                  {'market': 'BTC-RFR', 'korean_name': '리퍼리움', 'english_name': 'Refereum'},
                  {'market': 'BTC-RVN', 'korean_name': '레이븐코인', 'english_name': 'Ravencoin'},
                  {'market': 'BTC-BFT',
                   'korean_name': '비에프토큰',
                   'english_name': 'BnkToTheFuture'},
                  {'market': 'BTC-GO', 'korean_name': '고체인', 'english_name': 'GoChain'},
                  {'market': 'BTC-UPP',
                   'korean_name': '센티넬프로토콜',
                   'english_name': 'Sentinel Protocol'},
                  {'market': 'BTC-ENJ', 'korean_name': '엔진코인', 'english_name': 'Enjin'},
                  {'market': 'BTC-EDR', 'korean_name': '엔도르', 'english_name': 'Endor'},
                  {'market': 'BTC-MTL', 'korean_name': '메탈', 'english_name': 'Metal'},
                  {'market': 'BTC-PAX',
                   'korean_name': '팩소스스탠다드',
                   'english_name': 'Paxos Standard'},
                  {'market': 'BTC-MOC', 'korean_name': '모스코인', 'english_name': 'Moss Coin'},
                  {'market': 'BTC-ZIL', 'korean_name': '질리카', 'english_name': 'Zilliqa'},
                  {'market': 'BTC-BSV',
                   'korean_name': '비트코인에스브이',
                   'english_name': 'Bitcoin SV'},
                  {'market': 'BTC-IOST', 'korean_name': '아이오에스티', 'english_name': 'IOST'},
                  {'market': 'BTC-NCASH',
                   'korean_name': '뉴클리어스비전',
                   'english_name': 'Nucleus Vision'},
                  {'market': 'BTC-DENT', 'korean_name': '덴트', 'english_name': 'Dent'},
                  {'market': 'BTC-ELF', 'korean_name': '엘프', 'english_name': 'aelf'},
                  {'market': 'BTC-BTT', 'korean_name': '비트토렌트', 'english_name': 'BitTorrent'},
                  {'market': 'BTC-VITE', 'korean_name': '비트토큰', 'english_name': 'Vite'},
                  {'market': 'BTC-IOTX', 'korean_name': '아이오텍스', 'english_name': 'IoTeX'},
                  {'market': 'BTC-SOLVE', 'korean_name': '솔브케어', 'english_name': 'Solve.Care'},
                  {'market': 'BTC-NKN', 'korean_name': '엔케이엔', 'english_name': 'NKN'},
                  {'market': 'BTC-META', 'korean_name': '메타디움', 'english_name': 'Metadium'},
                  {'market': 'BTC-ANKR', 'korean_name': '앵커', 'english_name': 'Ankr'},
                  {'market': 'BTC-CRO',
                   'korean_name': '크립토닷컴체인',
                   'english_name': 'Crypto.com Chain'},
                  {'market': 'BTC-FSN', 'korean_name': '퓨전', 'english_name': 'Fusion'},
                  {'market': 'BTC-ORBS', 'korean_name': '오브스', 'english_name': 'Orbs'},
                  {'market': 'BTC-AERGO', 'korean_name': '아르고', 'english_name': 'Aergo'},
                  {'market': 'BTC-PI', 'korean_name': '플리안', 'english_name': 'Plian'},
                  {'market': 'BTC-ATOM', 'korean_name': '코스모스', 'english_name': 'Cosmos'},
                  {'market': 'BTC-STPT',
                   'korean_name': '에스티피',
                   'english_name': 'Standard Tokenization Protocol'},
                  {'market': 'BTC-LAMB', 'korean_name': '람다', 'english_name': 'Lambda'},
                  {'market': 'BTC-EOS', 'korean_name': '이오스', 'english_name': 'EOS'},
                  {'market': 'BTC-LUNA', 'korean_name': '루나', 'english_name': 'Luna'},
                  {'market': 'BTC-DAI', 'korean_name': '다이', 'english_name': 'Dai'},
                  {'market': 'BTC-MKR', 'korean_name': '메이커', 'english_name': 'Maker'},
                  {'market': 'BTC-BORA', 'korean_name': '보라', 'english_name': 'BORA'},
                  {'market': 'BTC-TSHP', 'korean_name': '트웰브쉽스', 'english_name': '12SHIPS'},
                  {'market': 'BTC-WAXP', 'korean_name': '왁스', 'english_name': 'WAX'},
                  {'market': 'BTC-MED', 'korean_name': '메디블록', 'english_name': 'MediBloc'},
                  {'market': 'BTC-MLK', 'korean_name': '밀크', 'english_name': 'MiL.k'},
                  {'market': 'BTC-PXL', 'korean_name': '픽셀', 'english_name': 'PIXEL'},
                  {'market': 'BTC-VET', 'korean_name': '비체인', 'english_name': 'VeChain'},
                  {'market': 'BTC-CHZ', 'korean_name': '칠리즈', 'english_name': 'Chiliz'},
                  {'market': 'BTC-FX', 'korean_name': '펑션엑스', 'english_name': 'Function X'},
                  {'market': 'BTC-OGN',
                   'korean_name': '오리진프로토콜',
                   'english_name': 'Origin Protocol'},
                  {'market': 'BTC-ITAM', 'korean_name': '아이텀', 'english_name': 'ITAM'},
                  {'market': 'BTC-XTZ', 'korean_name': '테조스', 'english_name': 'Tezos'},
                  {'market': 'BTC-HIVE', 'korean_name': '하이브', 'english_name': 'Hive'},
                  {'market': 'BTC-HBD', 'korean_name': '하이브달러', 'english_name': 'Hive Dollar'},
                  {'market': 'BTC-OBSR', 'korean_name': '옵저버', 'english_name': 'Observer'},
                  {'market': 'BTC-DKA', 'korean_name': '디카르고', 'english_name': 'dKargo'},
                  {'market': 'BTC-STMX', 'korean_name': '스톰엑스', 'english_name': 'StormX'},
                  {'market': 'BTC-AHT', 'korean_name': '아하토큰', 'english_name': 'AhaToken'},
                  {'market': 'BTC-PCI', 'korean_name': '페이코인', 'english_name': 'PayCoin'},
                  {'market': 'BTC-RINGX', 'korean_name': '링엑스', 'english_name': 'RINGX'},
                  {'market': 'BTC-LINK', 'korean_name': '체인링크', 'english_name': 'Chainlink'},
                  {'market': 'BTC-KAVA', 'korean_name': '카바', 'english_name': 'Kava'},
                  {'market': 'BTC-JST', 'korean_name': '저스트', 'english_name': 'JUST'},
                  {'market': 'BTC-CHR', 'korean_name': '크로미아', 'english_name': 'Chromia'},
                  {'market': 'BTC-DAD', 'korean_name': '다드', 'english_name': 'DAD'},
                  {'market': 'BTC-TON', 'korean_name': '톤', 'english_name': 'TON'},
                  {'market': 'BTC-CTSI', 'korean_name': '카르테시', 'english_name': 'Cartesi'},
                  {'market': 'BTC-DOT', 'korean_name': '폴카닷', 'english_name': 'Polkadot'},
                  {'market': 'BTC-COMP', 'korean_name': '컴파운드', 'english_name': 'Compound'},
                  {'market': 'BTC-SXP', 'korean_name': '스와이프', 'english_name': 'Swipe'},
                  {'market': 'BTC-HUNT', 'korean_name': '헌트', 'english_name': 'HUNT'},
                  {'market': 'BTC-ONIT', 'korean_name': '온버프', 'english_name': 'ONBUFF'},
                  {'market': 'BTC-CRV', 'korean_name': '커브', 'english_name': 'Curve'},
                  {'market': 'BTC-ALGO', 'korean_name': '알고랜드', 'english_name': 'Algorand'},
                  {'market': 'BTC-RSR',
                   'korean_name': '리저브라이트',
                   'english_name': 'Reserve Rights'},
                  {'market': 'BTC-OXT', 'korean_name': '오키드', 'english_name': 'Orchid'},
                  {'market': 'BTC-PLA', 'korean_name': '플레이댑', 'english_name': 'PlayDapp'},
                  {'market': 'BTC-MARO', 'korean_name': '마로', 'english_name': 'Maro'},
                  {'market': 'BTC-SAND', 'korean_name': '샌드박스', 'english_name': 'The Sandbox'},
                  {'market': 'BTC-SUN', 'korean_name': '썬', 'english_name': 'SUN'},
                  {'market': 'BTC-SRM', 'korean_name': '세럼', 'english_name': 'Serum'},
                  {'market': 'BTC-QTCON', 'korean_name': '퀴즈톡', 'english_name': 'Quiztok'},
                  {'market': 'BTC-MVL', 'korean_name': '엠블', 'english_name': 'MVL'},
                  {'market': 'BTC-GXC', 'korean_name': '지엑스체인', 'english_name': 'GXChain'},
                  {'market': 'BTC-AQT',
                   'korean_name': '알파쿼크',
                   'english_name': 'Alpha Quark Token'},
                  {'market': 'BTC-AXS',
                   'korean_name': '엑시인피니티',
                   'english_name': 'Axie Infinity'},
                  {'market': 'BTC-STRAX', 'korean_name': '스트라티스', 'english_name': 'Stratis'},
                  {'market': 'BTC-BCHA',
                   'korean_name': '비트코인캐시에이비씨',
                   'english_name': 'Bitcoin Cash ABC'},
                  {'market': 'BTC-GLM', 'korean_name': '골렘', 'english_name': 'Golem'},
                  {'market': 'BTC-FCT2', 'korean_name': '피르마체인', 'english_name': 'FirmaChain'},
                  {'market': 'BTC-SSX', 'korean_name': '썸씽', 'english_name': 'SOMESING'},
                  {'market': 'BTC-FIL', 'korean_name': '파일코인', 'english_name': 'Filecoin'},
                  {'market': 'BTC-UNI', 'korean_name': '유니스왑', 'english_name': 'Uniswap'},
                  {'market': 'BTC-BASIC', 'korean_name': '베이직', 'english_name': 'Basic'},
                  {'market': 'BTC-INJ',
                   'korean_name': '인젝티브프로토콜',
                   'english_name': 'Injective Protocol'},
                  {'market': 'BTC-PROM', 'korean_name': '프로메테우스', 'english_name': 'Prometeus'},
                  {'market': 'BTC-VAL', 'korean_name': '밸리디티', 'english_name': 'Validity'},
                  {'market': 'BTC-PSG',
                   'korean_name': '파리생제르맹',
                   'english_name': 'Paris Saint-Germain Fan Token'},
                  {'market': 'BTC-JUV',
                   'korean_name': '유벤투스',
                   'english_name': 'Juventus Fan Token'},
                  {'market': 'BTC-CBK', 'korean_name': '코박토큰', 'english_name': 'Cobak Token'},
                  {'market': 'BTC-FOR', 'korean_name': '포튜브', 'english_name': 'ForTube'},
                  {'market': 'BTC-BFC', 'korean_name': '바이프로스트', 'english_name': 'Bifrost'},
                  {'market': 'BTC-LINA', 'korean_name': '리니어파이낸스', 'english_name': 'Linear'},
                  {'market': 'BTC-HUM', 'korean_name': '휴먼스케이프', 'english_name': 'Humanscape'},
                  {'market': 'BTC-PICA', 'korean_name': '피카', 'english_name': 'Pica'},
                  {'market': 'BTC-CELO', 'korean_name': '셀로', 'english_name': 'Celo'},
                  {'market': 'BTC-IQ', 'korean_name': '에브리피디아', 'english_name': 'Everipedia'},
                  {'market': 'BTC-STX', 'korean_name': '스택스', 'english_name': 'Stacks'},
                  {'market': 'BTC-NEAR',
                   'korean_name': '니어프로토콜',
                   'english_name': 'NEAR Protocol'},
                  {'market': 'BTC-AUCTION', 'korean_name': '바운스토큰', 'english_name': 'Bounce'},
                  {'market': 'BTC-DAWN',
                   'korean_name': '던프로토콜',
                   'english_name': 'Dawn Protocol'},
                  {'market': 'BTC-FLOW', 'korean_name': '플로우', 'english_name': 'Flow'},
                  {'market': 'BTC-STRK', 'korean_name': '스트라이크', 'english_name': 'Strike'},
                  {'market': 'BTC-PUNDIX', 'korean_name': '펀디엑스', 'english_name': 'Pundi X'}]
