# Generated by Django 2.2.20 on 2021-04-27 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpBitMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10, unique=True, verbose_name='코인 종류')),
                ('korean_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='한국 코인 이름')),
                ('withdraw_fee', models.FloatField(verbose_name='출금수수로')),
                ('deposit_fee', models.FloatField(verbose_name='입금수수료')),
                ('minimum_with_draw_amount', models.FloatField(blank=True, null=True, verbose_name='최소출금액')),
            ],
            options={
                'verbose_name': '업비트 마켓 정보',
                'verbose_name_plural': '업비트 마켓 정보 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='upbitcoinexchange',
            name='volume',
            field=models.FloatField(verbose_name='거래량'),
        ),
        migrations.CreateModel(
            name='UpBitExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='코인 영어이름')),
                ('candle_date_time_kst', models.DateTimeField(verbose_name='코인 거래된 시간')),
                ('open_price', models.FloatField(verbose_name='시가')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('trade_price', models.IntegerField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
                ('market', models.ForeignKey(help_text='마켓', on_delete=django.db.models.deletion.PROTECT, to='up_bits.UpBitMarket')),
            ],
            options={
                'verbose_name': '업비트 코인 시세가 ',
                'verbose_name_plural': '업비트 코인 시세가  목록',
                'ordering': ['-candle_date_time_kst'],
            },
        ),
    ]
