# Generated by Django 2.2.20 on 2021-04-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0003_auto_20210427_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upbitexchange',
            name='trade_price',
        ),
    ]
