# Generated by Django 2.2.20 on 2021-04-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0004_remove_upbitexchange_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitmarket',
            name='withdraw_fee',
            field=models.FloatField(default=0.0, verbose_name='출금수수로'),
        ),
    ]
