# Generated by Django 2.2.20 on 2021-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0005_auto_20210427_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upbitmarket',
            name='deposit_fee',
        ),
        migrations.RemoveField(
            model_name='upbitmarket',
            name='minimum_with_draw_amount',
        ),
        migrations.RemoveField(
            model_name='upbitmarket',
            name='withdraw_fee',
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='binance_deposit_fee',
            field=models.FloatField(default=0.0, verbose_name='바이낸스입금수수료'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='binance_minimum_with_draw_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='바이낸스최소출금액'),
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='binance_withdraw_fee',
            field=models.FloatField(default=0.0, verbose_name='바이낸스출금수수로'),
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='up_bit_deposit_fee',
            field=models.FloatField(default=0.0, verbose_name='업비트입금수수료'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='up_bit_minimum_with_draw_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='업비트최소출금액'),
        ),
        migrations.AddField(
            model_name='upbitmarket',
            name='up_bit_withdraw_fee',
            field=models.FloatField(default=0.0, verbose_name='업비트출금수수로'),
        ),
    ]
