# Generated by Django 2.2.20 on 2021-04-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0006_auto_20210427_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_deposit_fee',
            field=models.FloatField(default=0.0, verbose_name='바이낸스입금수수료'),
        ),
    ]
