# Generated by Django 2.2.20 on 2021-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0008_auto_20210427_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_deposit_fee',
            field=models.FloatField(verbose_name='바이낸스입금수수료'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_minimum_with_draw_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='바이낸스최소출금액'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_withdraw_fee',
            field=models.FloatField(verbose_name='바이낸스출금수수로'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_deposit_fee',
            field=models.FloatField(verbose_name='업비트입금수수료'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_minimum_with_draw_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='업비트최소출금액'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_withdraw_fee',
            field=models.FloatField(verbose_name='업비트출금수수로'),
        ),
    ]
