# Generated by Django 2.2.20 on 2021-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0009_auto_20210427_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='upbitexchange',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='코인-거래소'),
        ),
    ]
