# Generated by Django 2.2.20 on 2021-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0011_auto_20210427_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitexchange',
            name='bit_coin_value',
            field=models.FloatField(default=0, verbose_name='비트코인 가격'),
        ),
    ]
