# Generated by Django 2.2.20 on 2021-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0013_auto_20210428_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='upbitexchange',
            name='deposit_amount_value',
            field=models.FloatField(default=0.0, verbose_name='기대수익률'),
        ),
    ]
