# Generated by Django 2.2.20 on 2021-05-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0014_upbitexchange_deposit_amount_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upbitexchange',
            old_name='deposit_amount_value',
            new_name='expected_revenue_rate',
        ),
    ]
