# Generated by Django 2.2.20 on 2021-05-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0016_upbitexchange_up_discrepancy_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_deposit_fee',
            field=models.FloatField(default=0.0, verbose_name='바이낸스입금수수료'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_minimum_with_draw_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='바이낸스최소출금액'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='binance_withdraw_fee',
            field=models.FloatField(default=0.0, verbose_name='바이낸스출금수수로'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_deposit_fee',
            field=models.FloatField(default=0.0, verbose_name='업비트입금수수료'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_minimum_with_draw_amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='업비트최소출금액'),
        ),
        migrations.AlterField(
            model_name='upbitmarket',
            name='up_bit_withdraw_fee',
            field=models.FloatField(default=0.0, verbose_name='업비트출금수수로'),
        ),
    ]
