# Generated by Django 2.2.20 on 2021-05-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0019_delete_upbitcoinexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='코인-거래소')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='코인 영어이름')),
                ('korean_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='한국 코인 이름')),
                ('withdraw_status', models.BooleanField(default=False, verbose_name='출금 상태')),
                ('deposit_status', models.BooleanField(default=False, verbose_name='입금 상태')),
                ('candle_date_time_kst', models.DateTimeField(verbose_name='코인 거래된 시간')),
                ('bit_coin_value', models.FloatField(default=0, verbose_name='비트코인 가격')),
                ('expected_revenue_rate', models.FloatField(default=0.0, verbose_name='기대수익률')),
                ('discrepancy_rate', models.FloatField(default=0.0, verbose_name='괴리율 정도')),
                ('open_price', models.FloatField(verbose_name='시가')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
                ('transaction_price', models.FloatField(default=0.0, verbose_name='거래대금')),
                ('market', models.ForeignKey(help_text='마켓', on_delete=django.db.models.deletion.CASCADE, to='up_bits.UpBitMarket')),
            ],
            options={
                'verbose_name': '업비트 코인 시세가 ',
                'verbose_name_plural': '업비트 코인 시세가  목록',
                'ordering': ['-candle_date_time_kst'],
            },
        ),
    ]
