# Generated by Django 2.2.20 on 2021-04-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('up_bits', '0006_auto_20210427_0757'),
        ('bit_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitFinanceExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='코인 영어이름')),
                ('korean_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='한국 코인 이름')),
                ('candle_date_time_kst', models.DateTimeField(verbose_name='코인 거래된 시간')),
                ('open_price', models.FloatField(verbose_name='시가')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
                ('market', models.ForeignKey(help_text='마켓', on_delete=django.db.models.deletion.PROTECT, to='up_bits.UpBitMarket')),
            ],
            options={
                'verbose_name': '바이낸스 코인 시세가 ',
                'verbose_name_plural': '바이낸스 코인 시세가  목록',
                'ordering': ['-candle_date_time_kst'],
            },
        ),
    ]
