# Generated by Django 2.2.20 on 2021-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_finance', '0003_bitfinanceexchange_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='bit_coin_value',
            field=models.CharField(default=0, max_length=50, verbose_name='비트코인 가격'),
        ),
        migrations.AlterField(
            model_name='bitfinanceexchange',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='코인-거래소'),
        ),
    ]
