# Generated by Django 2.2.20 on 2021-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_finance', '0005_auto_20210427_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='deposit_status',
            field=models.BooleanField(default=False, verbose_name='입금 상태'),
        ),
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='withdraw_status',
            field=models.BooleanField(default=False, verbose_name='출금 상태'),
        ),
    ]
