# Generated by Django 2.2.20 on 2021-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_finance', '0006_auto_20210428_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='binance_discrepancy_rate',
            field=models.FloatField(default=0.0, verbose_name='괴리율 정도'),
        ),
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='expected_revenue_rate',
            field=models.FloatField(default=0.0, verbose_name='기대수익률'),
        ),
    ]
