# Generated by Django 2.2.20 on 2021-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_finance', '0007_auto_20210503_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitfinanceexchange',
            name='transaction_price',
            field=models.FloatField(default=0.0, verbose_name='거래대금'),
        ),
    ]
